// COPYRIGHT (C) 2018 TEKNIQUE LIMITED
// ALL RIGHTS RESERVED. FOR LICENSING INFORMATION CONTACT LICENSE@TEKNIQUE.COM
#ifndef _AMBA_MSG_H_
#define _AMBA_MSG_H_

extern int amba_msg_handler(void)

#endif
