/*
 *
 * idsp_test
 *
 * History:
 *	2013/09/05 - [Dylan] Created this file
 *
 * Description :
 *	Load the tuned file which generated by Img tuning tool.
 *
 * Copyright (C) 2015 Ambarella, Inc.
 *
 * This file and its contents ("Software") are protected by intellectual
 * property rights including, without limitation, U.S. and/or foreign
 * copyrights. This Software is also the confidential and proprietary
 * information of Ambarella, Inc. and its licensors. You may not use, reproduce,
 * disclose, distribute, modify, or otherwise prepare derivative works of this
 * Software or any portion thereof except pursuant to a signed license agreement
 * or nondisclosure agreement with Ambarella, Inc. or its authorized affiliates.
 * In the absence of such an agreement, you agree to promptly notify and return
 * this Software to Ambarella, Inc.
 *
 * THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF NON-INFRINGEMENT,
 * MERCHANTABILITY, AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL AMBARELLA, INC. OR ITS AFFILIATES BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; COMPUTER FAILURE OR MALFUNCTION; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 */

#ifndef _AMBA_TEXT_HDLR_H_
#define _AMBA_TEXT_HDLR_H_

#include "AmbaDataType.h"
#include "AmbaDSP_ImgDef.h" // amba_img_dsp_mode_cfg_t need
#include "AmbaImgCalibItuner.h"

#ifndef FALSE			/* in case these macros already exist */
#define FALSE	0		/* values of boolean */
#endif  /* FALSE */


int TextHdlr_Init(void);
int TextHdlr_Save_IDSP(amba_img_dsp_mode_cfg_t Mode, char *Filepath);
int TextHdlr_Load_IDSP(char *Filepath);
int TextHdlr_Load_Data(Ituner_Ext_File_Type_e Ext_File_Type, Ituner_Ext_File_Param_s* Ext_File_Param);
int TextHdlr_Save_Data(Ituner_Ext_File_Type_e Ext_File_Type, Ituner_Ext_File_Param_s* Ext_File_Param);
int TextHdlr_Execute_IDSP(int fd_iav, amba_img_dsp_mode_cfg_t Mode, AMBA_ITUNER_PROC_INFO_s *ProcInfo);
int TextHdlr_Get_SystemInfo(ITUNER_SYSTEM_s *System);
int TextHdlr_Set_SystemInfo(ITUNER_SYSTEM_s *System);
int TextHdlr_Get_ItunerInfo(ITUNER_INFO_s *ItunerInfo);
int TextHdlr_Load_ituner(char* ituner_stream);
int TextHdlr_set_ituner(u8* ituner_stream,int size);
#endif /* _AMBA_TEXT_HDLR_H_ */
