/*
 *
 * idsp_test
 *
 * History:
 *	2013/09/05 - [Dylan] Created this file
 *
 * Description :
 *	Load the tuned file which generated by Img tuning tool.
 *
 * Copyright (C) 2015 Ambarella, Inc.
 *
 * This file and its contents ("Software") are protected by intellectual
 * property rights including, without limitation, U.S. and/or foreign
 * copyrights. This Software is also the confidential and proprietary
 * information of Ambarella, Inc. and its licensors. You may not use, reproduce,
 * disclose, distribute, modify, or otherwise prepare derivative works of this
 * Software or any portion thereof except pursuant to a signed license agreement
 * or nondisclosure agreement with Ambarella, Inc. or its authorized affiliates.
 * In the absence of such an agreement, you agree to promptly notify and return
 * this Software to Ambarella, Inc.
 *
 * THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF NON-INFRINGEMENT,
 * MERCHANTABILITY, AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL AMBARELLA, INC. OR ITS AFFILIATES BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; COMPUTER FAILURE OR MALFUNCTION; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 */

#ifndef _AMBA_TUNE_HDLR_MANAGER_H_
#define _AMBA_TUNE_HDLR_MANAGER_H_

#include "AmbaImgCalibItuner.h" // Note: Ituner_Ext_File_Type_e Need

typedef enum {
    TEXT_TUNE = 0,
    USB_TUNE,
    MAX_TUNE,
} TuneHdlr_Mode_e;

int AmbaTUNE_Init(void);
void AmbaTUNE_Change_Parser_Mode(TuneHdlr_Mode_e Parser_Mode);
int AmbaTUNE_Save_IDSP(amba_img_dsp_mode_cfg_t Mode, char *Filepath);
int AmbaTUNE_Load_IDSP(char *Filepath);
int AmbaTUNE_Save_Data(Ituner_Ext_File_Type_e Ext_File_Type, Ituner_Ext_File_Param_s *Ext_File_Param);
int AmbaTUNE_Load_Data(Ituner_Ext_File_Type_e Ext_File_Type, Ituner_Ext_File_Param_s *Ext_File_Param);
int AmbaTUNE_Execute_IDSP(int fd_iav, amba_img_dsp_mode_cfg_t Mode, AMBA_ITUNER_PROC_INFO_s *ProcInfo);
int AmbaTUNE_Get_SystemInfo(ITUNER_SYSTEM_s *System);
int AmbaTUNE_Set_SystemInfo(ITUNER_SYSTEM_s *System);
int AmbaTUNE_Get_ItunerInfo(ITUNER_INFO_s *ItunerInfo);
int AmbaTUNE_apply_ituner_stream(u8* ituner_stream,int size);
int AmbaTUNE_load_ituner_stream(char *ituner_stream);
#endif /* _AMBA_TUNE_HDLR_MANAGER_H_ */
