/*
 *
 * idsp_test
 *
 * History:
 *	2015/09/10 - [Jingyang Qiu] Created this file
 *
 * Description :
 *	Load the tuned file which generated by Img tuning tool.
 *
 * Copyright (C) 2015 Ambarella, Inc.
 *
 * This file and its contents ("Software") are protected by intellectual
 * property rights including, without limitation, U.S. and/or foreign
 * copyrights. This Software is also the confidential and proprietary
 * information of Ambarella, Inc. and its licensors. You may not use, reproduce,
 * disclose, distribute, modify, or otherwise prepare derivative works of this
 * Software or any portion thereof except pursuant to a signed license agreement
 * or nondisclosure agreement with Ambarella, Inc. or its authorized affiliates.
 * In the absence of such an agreement, you agree to promptly notify and return
 * this Software to Ambarella, Inc.
 *
 * THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF NON-INFRINGEMENT,
 * MERCHANTABILITY, AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL AMBARELLA, INC. OR ITS AFFILIATES BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; COMPUTER FAILURE OR MALFUNCTION; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 */

#include <unistd.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <errno.h>

#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>


#include <sys/stat.h>
#include <sys/ioctl.h>
#include <sys/mman.h>
#include <sys/time.h>
#include <sys/wait.h>
#include <time.h>
#include <assert.h>
#include <getopt.h>
#include <sched.h>
#include <signal.h>
#include "types.h"

#include "iav_ioctl.h"
#include "ambas_imgproc_arch.h"
#include "ambas_imgproc_ioctl_arch.h"
#include "img_adv_struct_arch.h"

#include <pthread.h>
#include <semaphore.h>

#include "AmbaDataType.h"
#include "AmbaDSP_ImgDef.h"
#include "AmbaDSP_ImgUtility.h"
#include "AmbaDSP_ImgFilter.h"

#include "dsp_cmd.h"
#include "dsp_imgknl_if_a12.h"

#include "AmbaTUNE_HdlrManager.h"
#include "AmbaDSP_ImgLowIsoFilter.h"

#define AmbaPrint(format, arg...)	printf(format"\n", ##arg)
#ifndef ROUND_UP
#define ROUND_UP(size, align) (((size) + ((align) - 1)) & ~((align) - 1))
#endif


//u8 IkWorkingBuf[509184+12+16];
u8 IkWorkingBuf[2<<20];


typedef struct _AMBA_DSP_IMG_TEST_IS2_s_
{
    UINT32 init;

    amba_img_dsp_mode_cfg_t Mode;

    char Warp1Fn[64];
    char Warp2Fn[64];
    UINT8 *Warp1;
    UINT8 *Warp2;
    UINT32 Warp1Len;
    UINT32 Warp2Len;
    int Blend;
    UINT32 Decay;
    UINT32 WarpGridWidth;
    UINT32 WarpGridHeight;
} AMBA_DSP_IMG_TEST_IS2_s;

AMBA_DSP_IMG_TEST_IS2_s gTestIS2 = {0};
int fd_iav;

amba_img_dsp_pipe_info_t PipeInfo;//, PipeInfo_S;
amba_img_dsp_arch_info_t ArchInfo = {0};
amba_img_dsp_ctx_info_t DestCtx, SrcCtx;
amba_img_dsp_cfg_info_t CfgInfo;
static int test_is2_init(u8* mem)
{
    INT32 Rval = 0, TotalSize = 0;

    memset(&PipeInfo, 0x0, sizeof(amba_img_dsp_pipe_info_t));
    memset(&DestCtx, 0x0, sizeof(amba_img_dsp_ctx_info_t));
    memset(&SrcCtx, 0x0, sizeof(amba_img_dsp_ctx_info_t));

    PipeInfo.Pipe = AMBA_DSP_IMG_PIPE_VIDEO;
    PipeInfo.CtxBufNum = 1;
    PipeInfo.CfgBufNum = 2;


//    ArchInfo.pWorkBuf = (UINT8*) IkWorkingBuf;
//    ArchInfo.BufSize = sizeof(IkWorkingBuf);
	ArchInfo.pWorkBuf = mem;
	ArchInfo.BufSize = 2<<20;
	ArchInfo.BufNum = 1;
    ArchInfo.PipeNum = 1;
    ArchInfo.pPipeInfo[0] = &PipeInfo;
//    ArchInfo.pPipeInfo[1] = &PipeInfo_S;
    TotalSize = amba_img_dsp_query_arch_mem_size(&ArchInfo);
    printf("test_is2_init(): Total size needed %d Bytes\n", TotalSize);
    //AmbaDSP_ImgSetMemory((UINT32)&IkWorkingBuf, sizeof(IkWorkingBuf));
    //AmbaPrint("test_is2_init(): AmbaDSP_ImgUtilitySetMemory done");
    amba_img_dsp_init_arch(&ArchInfo);

    mem_op_t op;
    op._free = free;
    op._malloc = malloc;
    op._memcpy = memcpy;
    op._memset = memset;
    img_dsp_register_mem(&op);
    img_dsp_register_print(printf);
    img_dsp_register_ioc((img_ioctl)ioctl);

    DestCtx.Pipe = AMBA_DSP_IMG_PIPE_VIDEO;
    DestCtx.CtxId = 0;
//    AmbaDSP_ImgUtilityInitCtx(0, 1, DestCtx, SrcCtx);
    amba_img_dsp_init_ctx(0, 1, 1, &DestCtx, &SrcCtx);

//    DestCtx.Pipe = AMBA_DSP_IMG_PIPE_STILL;
//    DestCtx.CtxId = 0;
//    amba_img_dsp_init_ctx(0, 1, DestCtx, SrcCtx);
//    CfgInfo.Pipe = AMBA_DSP_IMG_PIPE_STILL;
//    CfgInfo.CfgId = 0;
    CfgInfo.Pipe = AMBA_DSP_IMG_PIPE_VIDEO;
    CfgInfo.CfgId = 0;
    amba_img_dsp_init_cfg(&CfgInfo, AMBA_DSP_IMG_ALGO_MODE_LISO);
    CfgInfo.Pipe = AMBA_DSP_IMG_PIPE_VIDEO;
    CfgInfo.CfgId = 1;
    amba_img_dsp_init_cfg(&CfgInfo, AMBA_DSP_IMG_ALGO_MODE_LISO);

    return Rval;
}

static int test_ituner(int fd_iav, char* file_name)
{
	int Rval = -1;
	AmbaTUNE_Change_Parser_Mode(TEXT_TUNE);
	if (0 != AmbaTUNE_Init()) {
	    printf("%s() %d, call AmbaTUNE_Init() Fail", __func__, __LINE__);
	    return Rval;
	}
	//HENRY TBD Disable 3A

	if (0 != AmbaTUNE_Load_IDSP(file_name)) {
	    printf("%s() %d, call AmbaTUNE_Load_IDSP(%s) Fail", __func__, __LINE__, file_name);
	     return Rval;
	}
//	getchar();
	ITUNER_INFO_s ItunerInfo;
	if (0 != AmbaTUNE_Get_ItunerInfo(&ItunerInfo)) {
	    printf("%s() %d, call AmbaTUNE_Get_ItunerInfo() Fail", __func__, __LINE__);
	     return Rval;
	}
	memcpy(&gTestIS2.Mode, &ItunerInfo.TuningAlgoMode, sizeof(amba_img_dsp_mode_cfg_t));
	AMBA_ITUNER_PROC_INFO_s ProcInfo;
	memset(&ProcInfo, 0, sizeof(AMBA_ITUNER_PROC_INFO_s));
	ProcInfo.HisoBatchId = 0;
	gTestIS2.Mode.BatchId =0xff; // FIXME
	printf("algo mode %d\n", gTestIS2.Mode.AlgoMode);
	if (0 != AmbaTUNE_Execute_IDSP(fd_iav, gTestIS2.Mode, &ProcInfo)) {
	    printf("%s() %d, call AmbaTUNE_Execute_IDSP() Fail", __func__, __LINE__);
	     return Rval;
	}
	Rval = 0;

	return Rval;
}


static int test_ituner_save(int fd_iav, char* file_name)
{
	int Rval = -1;

	do{
		AmbaTUNE_Change_Parser_Mode(TEXT_TUNE);
		if (0 != AmbaTUNE_Init()) {
		    AmbaPrint("%s() %d, call AmbaTUNE_Init() Fail", __func__, __LINE__);
		    return Rval;
		}

		if (0 != AmbaTUNE_Save_IDSP(gTestIS2.Mode, file_name)) {
			AmbaPrint("%s() %d, call AmbaTUNE_Save_IDSP(FilePath:%s) Fail", __func__, __LINE__, file_name);
			break;
		}

		Rval = 0;
	}while(0);

	return Rval;
}

void idsp_dump_bin(int fd_iav, u8 id)
{
	char bin_filename[32];
	int fd_bin_dump = -1;
	u8 *bin_buffer = NULL;
	idsp_config_info_t	dump_idsp_info;
	int rval = -1;

	if(id >= 8 && id != 100){
		printf("err: unknow id section.\n");
		return;
	}

	if(bin_buffer == NULL){
		bin_buffer = (u8*)malloc(MAX_DUMP_BUFFER_SIZE);
	}
	if(bin_buffer != NULL){
		memset(bin_buffer, 0, MAX_DUMP_BUFFER_SIZE);
	}else{
		return;
	}

	dump_idsp_info.id_section = id;
	dump_idsp_info.addr = bin_buffer;

	//while(rval < 0){
		rval = ioctl(fd_iav, IAV_IOC_IMG_DUMP_IDSP_SEC, &dump_idsp_info);
		if (rval < 0) {
			perror("IAV_IOC_IMG_DUMP_IDSP_SEC");
		}
	//	sleep(1);
	//	printf("\n");
	//}

	sprintf(bin_filename, "/mnt/idsp_dump_bin_%d.bin",id);
	fd_bin_dump = open(bin_filename, O_WRONLY | O_CREAT, 0666);
	if(fd_bin_dump < 0){
		printf("Failed to open bin file %s.\n",bin_filename);
		goto idsp_dump_exit;
	}

	if (write(fd_bin_dump, bin_buffer, dump_idsp_info.addr_long) < 0) {
		printf("Failed to write to bin file %s.\n",bin_filename);
		goto idsp_dump_exit;
	}

idsp_dump_exit:
	if(bin_buffer != NULL){
		free(bin_buffer);
		bin_buffer = NULL;
	}

	if(fd_bin_dump > 0){
		close(fd_bin_dump);
		fd_bin_dump = -1;
	}
}


#define MAX_RAW_FILE_NUM		(3)
#if 0
static int load_hiso_config(void)
{
	u8 * start_addr = NULL;
	int i, fd_raw;
	int count, dpitch, total_size, max_size;
	struct iav_mmap_info_s map;
	char fn[64];

	if (ioctl(fd_iav, IAV_IOC_MAP_IMGPROC, &map) < 0) {
		perror("IAV_IOC_MAP_IMGPROC");
		return -1;
	}
	printf("IAV_IOC_MAP_IMGPROC %p 0x%x\n", map.addr, map.length);
	max_size = map.length / 2 / (MAX_RAW_FILE_NUM + 1);

	start_addr = map.addr;
	total_size = 1<<20;

	/* Load raw image data file */
	for (i = 0; i < MAX_RAW_FILE_NUM; ++i, start_addr += max_size) {
		/*if (raw_file_path_flag & (1 << i)) {
			fd_raw = -1;
			if ((fd_raw = open(raw_file_path[i], O_RDONLY, 0)) < 0) {
				printf("Failed to open file [%s].\n", raw_file_path[i]);
				return -1;
			}
			if ((count = read(fd_raw, start_addr, total_size)) != total_size) {
				printf("Read file [%s] error, it is not equal to the correct size [%d].\n",
					raw_file_path[i], total_size);
				return -1;
			}
			close(fd_raw);
			hiso.sensor_raw_addr[i] = (u32)start_addr;
		}*/
	}

	/* Load HISO config file */
	printf("map %p 0x%x, start %p\n", map.addr, map.length, start_addr);
	fd_raw = -1;
	sprintf(fn, "/mnt/a7s_hiso_data_640x480_HI5_0.y");
	if ((fd_raw = open(fn, O_RDONLY, 0)) < 0) {
		printf("Failed to open file [%s].\n", fn);
		return -1;
	}
	printf("cfg start addr %p\n", start_addr);
	count = read(fd_raw, start_addr, total_size);
	printf("read file %d cnt %d\n", fd_raw, count);
	close(fd_raw);
	/*hiso.hiso_config_addr = (u32)start_addr;
	hiso.raw_width = raw_width;
	hiso.raw_height = raw_height;
	hiso.raw_compression = raw_comp;

	printf("\nHISO Settings:\n");
	printf("   RAW image 0: [%s]\n", raw_file_path[0]);
	printf("   RAW image 1: [%s]\n", raw_file_path[1]);
	printf("   RAW image 2: [%s]\n", raw_file_path[2]);
	printf("   HISO CFG file: [%s]\n", hiso_cfg_file_path);
	printf("   RAW size: [%dx%d]\n", raw_width, raw_height);
	printf("   RAW compress [%d]\n\n", raw_comp);
	if (ioctl(fd_iav, IAV_IOC_SET_HISO_VIDEO_SETUP_EX, &hiso) < 0) {
		perror("IAV_IOC_HISO_SETUP_TEST");
		return -1;
	}*/

	return 0;
}
#endif

static const char* short_options = "l:ds:m:ip:P:n:rf:RC:w:h:B:atD:g:o:c:F:";
static struct option long_options[] = {
	{"load", 1, 0, 'l'},
	{"debug", 0, 0, 'd'},
	{"step", 1, 0, 's'},
	{"mode", 1, 0, 'm'},

	{"file-input", 0, 0, 'i'},
	{"path", 1, 0, 'p'},
	{"prefix", 1, 0, 'P'},
	{"number", 1, 0, 'n'},

	{"retrieve", 0, 0, 'r'},
	{"file", 1, 0, 'f'},
	{"record", 1, 0, 'R'},
	{"cycle", 1, 0, 'C'},
	{"width", 1, 0, 'w'},
	{"height", 1, 0, 'h'},
	{"batch", 1, 0, 'B'},
	{"slave", 1, 0, 'a'},
	{"test", 1, 0, 't'},
	{"dump", 1, 0, 'D'},
	{"gain", 1, 0, 'g'},
	{"row", 1, 0, 'o'},
	{"convert", 1, 0, 'c'},
	{"Frame",1,0,'F'}
};

struct hint_s {
	const char *arg;
	const char *str;
};
static const struct hint_s hint[] = {
	{"-l", "load ituner file"},
	{"-d", "\tenable debug"},
	{"-s", "\tdebug step"},
	{"-m", "\tdebug mode"},
	{"-F", "\tdebug frame"},
	{"exp", "\ttest_ituner -l filename [-d] [-s 0] [-m 5]"},
	{"-i", "\tfeed raw"},
	{"-p", "\tspecify raw file path"},
	{"-P", "\tspecify raw file prefix name"},
	{"-n", "\ttotal RAW file number"},
	{"-w", "\tRAW file width"},
	{"-h", "\tRAW file height"},
	{"-B", "\tRAW file number in one batch"},
	{"exp", "\ttest_ituner -i -p /sdcard/raw_in -P hiso_imx104_ -n 90 -w 1280 -h 720"},
	{"-r", "\tretrieve debug dump, in /mnt/debug"},
	{"exp", "\ttest_ituner -r"},
	{"-D", "\tDump idsp section, in /mnt/debug"},
};
void print_help(void)
{
	int cnt = sizeof(hint)/sizeof(hint[0]);
	int i;
	for(i=0; i<cnt; i++) {
		printf("%s %s\n", hint[i].arg, hint[i].str);
	}
}
typedef enum{
	LOAD_CONFIG = 1,
	FEED_RAW,
	PRE_FEED_RAW,
	DUMP_DEBUG,
	SLAVE_MODE,
	TEST_MODE,
	DUMP_SECTION,
	SENSOR_CNTL,
	CONVERT_MODE,
}ituner_work_mode;

static ituner_work_mode work_mode;
static int debug_step, debug_mode, debug_enable,debug_frame;
static int enable_record;
static int feed_raw_number;
static char file_name[128];
static char folder_name[128];
static char prefix_name[128];
static int loop_cycle = 1;
static int loop_raw_cnt;
static int file_width, file_height, batch_num = 5;
static int sec_id=0;

static int sensor_gain_index = -1;
static int sensor_sht_row = -1;

//static u8 mem_section;

static int ituner_init_param(int argc, char **argv)
{
	int ch;
	int option_index = 0;

	opterr = 0;
	while ((ch = getopt_long(argc, argv, short_options, long_options, &option_index)) != -1) {
		switch(ch) {
		case 'l':
			work_mode = LOAD_CONFIG;
			memcpy(file_name, optarg, 128);
			break;
		case 'd':
			debug_enable = 1;
			break;
		case 's':
			debug_step = atoi(optarg);
			break;
		case 'm':
			debug_mode = atoi(optarg);
			break;
		case 'i':
			work_mode = FEED_RAW;
			break;
		case 'F':
		        debug_frame =atoi(optarg);
		        break;
		case 'p':
			memcpy(folder_name, optarg, 128);
			break;
		case 'P':
			memcpy(prefix_name, optarg, 128);
			break;
		case 'n':
			feed_raw_number = atoi(optarg);
			break;
		case 'r':
//			mem_section = (u8)atoi(optarg);
			work_mode = DUMP_DEBUG;
			break;
		case 'f':
			memcpy(file_name, optarg, 128);
			break;
		case 'R':
			enable_record = 1;
			break;
		case 'C':
			loop_cycle = atoi(optarg);
			if(loop_cycle <= 0) {
				printf("loop cycle shall be positive integer\n");
				return -1;
			}
			break;
		case 'w':
			file_width = atoi(optarg);
			break;
		case 'h':
			file_height = atoi(optarg);
			break;
		case 'B':
			batch_num = atoi(optarg);
			break;
		case 'a':
			work_mode = SLAVE_MODE;
			break;
		case 't':
			work_mode = TEST_MODE;
			break;
		case 'D':
			work_mode = DUMP_SECTION;
			sec_id = atoi(optarg);
			break;
		case 'g':
			work_mode = SENSOR_CNTL;
			sensor_gain_index = atoi(optarg);
			break;
		case 'o':
			work_mode = SENSOR_CNTL;
			sensor_sht_row = atoi(optarg);
			break;
		case 'c':
			work_mode = CONVERT_MODE;
			memcpy(file_name, optarg, 128);
			printf("conver %s\n", file_name);
			break;
		default:
			printf("unknown option %c\n", ch);
			return -1;
		}
	}

	return 0;
}

sem_t feed_sem;
sem_t feed_ready_sem;
sem_t rec_sem;
u8 *feed_addr = NULL;
u8 *cfg_start_addr = NULL, *ik_start_addr = NULL;
u8* dest[2];
int total_raw_cnt = 0;
char recv_buf[1024];
struct sockaddr_in server, client;

void rec_loop(void* arg)
{
	sem_wait(&rec_sem);
	system("test_encode -A -h720p -e");
}

void feed_loop(void* arg)
{
	int fd_raw,i=0;
	int raw_width= 1280, raw_height=720;
	char fn[128];
	int dpitch;// = ROUND_UP((raw_width << 1), 32);
	int raw_size;// = dpitch*raw_height;
	u8 dest_num = 0;
	u8 *buf;
	int temp_cnt;

	raw_width = file_width;
	raw_height = file_height;
	dpitch = ROUND_UP((raw_width << 1), 32);
	raw_size = dpitch*raw_height;

	u8* pre_buf = malloc(raw_size);
	for(i=0; i<feed_raw_number; i++) {
		sprintf(fn, "%s/%s%d.raw", folder_name, prefix_name, i);
		if((fd_raw = open(fn, O_RDONLY, 0)) < 0){
				printf("Failed to open file [%s].\n", fn);
				return;
			}
		if(read(fd_raw, pre_buf, raw_size)!=raw_size){
			printf("read %s fail\n", fn);
			return;
		}
		close(fd_raw);
		printf("\r caching raw file %d", i);
		fflush(stdout);
	}
	printf("\n");
	free(pre_buf);
	pre_buf = NULL;
	temp_cnt = 0;
	while(1){
		sem_wait(&feed_sem);
		if(total_raw_cnt >= loop_raw_cnt)
			continue;
		if(temp_cnt >= feed_raw_number)
			temp_cnt = 0;
		buf = dest[dest_num];
		for(i=0; i< batch_num; i++) {
			#if 0
			memcpy(buf + i*raw_size, pre_buf+total_raw_cnt*raw_size, raw_size);
			total_raw_cnt++;
			#else
			sprintf(fn, "%s/%s%d.raw", folder_name, prefix_name, temp_cnt);
			if((fd_raw = open(fn, O_RDONLY, 0)) < 0){
				printf("Failed to open file [%s].\n", fn);
				return;
			}
			if(read(fd_raw, buf + i*raw_size, raw_size)!=raw_size){
				printf("read %s fail\n", fn);
				return;
			}
			close(fd_raw);
			total_raw_cnt ++;
			temp_cnt++;
			printf("load %s to %p, total %d\n", fn, buf, total_raw_cnt);
			#endif
		}
		dest_num ^= 1;
		sem_post(&feed_ready_sem);
	}

	return;
}

int process_cmd(void* buf)
{
	char shell_cmd[128];

	memcpy(shell_cmd, buf, 128);
	system(shell_cmd);

	return 0;
}

int creat_socket_server(in_port_t in_port, in_addr_t in_addr)
{
	int socket_fd, on;
	struct timeval timeout = {10,0};

	server.sin_family = AF_INET;
	server.sin_port = in_port;
	server.sin_addr.s_addr = in_addr;

	if((socket_fd = socket(AF_INET, SOCK_STREAM, 0))<0) {
		perror("listen socket uninit\n");
		return -1;
	}

	setsockopt(socket_fd, SOL_SOCKET, SO_RCVTIMEO, (char*)&timeout, sizeof(timeout));
	setsockopt(socket_fd, SOL_SOCKET, SO_REUSEADDR, &on, sizeof(int) );
	printf("on %x\n", on);
	if((bind(socket_fd, (struct sockaddr *)&server, sizeof(server)))<0) {
		perror("cannot bind srv socket\n");
		return -1;
	}

	if(listen(socket_fd, SOMAXCONN)<0) {
		perror("cannot listen");
		close(socket_fd);
		return -1;
	}

	return socket_fd;
}

/*
int map_bsb(void)
{
	struct iav_querybuf querybuf;

	querybuf.buf = IAV_BUFFER_BSB;
	if (ioctl(fd_iav, IAV_IOC_QUERY_BUF, &querybuf) < 0) {
		perror("IAV_IOC_QUERY_BUF");
		return -1;
	}

	bsb_size = querybuf.length;
	bsb_mem = mmap(NULL, bsb_size * 2, PROT_READ, MAP_SHARED, fd_iav, querybuf.offset);
	if (bsb_mem == MAP_FAILED) {
		perror("mmap (%d) failed: %s\n");
		return -1;
	}

	printf("bsb_mem = 0x%x, size = 0x%x\n", (u32)bsb_mem, bsb_size);
	return 0;
}
*/

int main(int argc, char **argv)
{
	struct iav_querybuf querybuf;
	pthread_t thread_id;
	extern int amba_img_dsp_set_debug_mode(amba_img_dsp_mode_cfg_t *pMode, AMBA_DSP_IMG_DEBUG_MODE_s *pDebugMode);
	extern int amba_img_dsp_get_debug_mode(amba_img_dsp_mode_cfg_t *pMode, AMBA_DSP_IMG_DEBUG_MODE_s *pDebugMode);
	extern int AmbaDSP_ImgLowIsoPrintCfg(amba_img_dsp_cfg_info_t CfgInfo);
	extern int AmbaDSP_ImgLowIsoDumpCfg(amba_img_dsp_cfg_info_t CfgInfo, char *dir);
	extern int img_dsp_low_iso_set_mem_info(u32 user_start, u32 phys_start, u32 mask);

	if(argc<=1)
		print_help();
	if (ituner_init_param(argc, argv) < 0) {
		return -1;
	}
	if ((fd_iav = open("/dev/iav", O_RDWR, 0)) < 0) {
		perror("open /dev/iav");
		return -1;
	}
	querybuf.buf = IAV_BUFFER_IMG;
	if (ioctl(fd_iav, IAV_IOC_QUERY_BUF, &querybuf) < 0) {
		perror("IAV_IOC_QUERY_BUF");
		return -1;
	}
	printf("memory %p size %dMB from IAV\t", (void*)querybuf.offset, querybuf.length>>20);
	ik_start_addr = mmap(NULL, querybuf.length, PROT_READ|PROT_WRITE, MAP_SHARED, fd_iav, querybuf.offset);
	if (ik_start_addr == MAP_FAILED) {
		perror("mmap (%d) failed: %s\n");
		return -1;
	}
	printf("map to %p\n", ik_start_addr);
	u32 phy_addr =querybuf.offset;
	img_dsp_low_iso_set_mem_info((u32)ik_start_addr, phy_addr, 0x3fffffff);

	cfg_start_addr = ik_start_addr + 0x400000;
	feed_addr = cfg_start_addr + 0x100000;

	if (ioctl(fd_iav, IAV_IOC_IMG_RESET_RAW2ENC_NI) < 0)
		printf("IAV_IOC_IMG_RESET_RAW2ENC_NI error\n");

	sem_init(&feed_sem, 0, 0);
	sem_init(&feed_ready_sem, 0, 0);
	sem_init(&rec_sem, 0, 0);

	switch(work_mode) {
    case LOAD_CONFIG:
        printf("load ituner file %s, debug step%d mode%d\n", file_name, debug_step, debug_mode);
        test_is2_init(ik_start_addr);
        test_ituner(fd_iav, file_name);
        AMBA_DSP_IMG_DEBUG_MODE_s debug = { 0 };
        debug.Step = debug_step;
        debug.Mode = debug_mode;
        debug.PicNum = debug_frame;
        if (debug_enable)
            amba_img_dsp_set_debug_mode(&gTestIS2.Mode, &debug);
        amba_img_dsp_post_exe_cfg(fd_iav, &gTestIS2.Mode, AMBA_DSP_IMG_CFG_EXE_PARTIALCOPY, 1);
        CfgInfo.CfgId = gTestIS2.Mode.ConfigId;

        if (debug_enable) {
            AmbaDSP_ImgLowIsoDumpCfg(CfgInfo, "/mnt");
            AmbaDSP_ImgLowIsoPrintCfg(CfgInfo);
        }

#if 0
			debug.Step = debug_step;
			debug.Mode = debug_mode;
			if(debug_enable)
				amba_img_dsp_set_debug_mode(&gTestIS2.Mode, &debug);
			amba_img_dsp_post_exe_cfg(fd_iav, &gTestIS2.Mode, 2, 1);
			CfgInfo.CfgId = gTestIS2.Mode.ConfigId;
//			AmbaDSP_ImgHighIsoDumpCfg(CfgInfo, "/mnt/cfg");
//			AmbaDSP_ImgHighIsoPrintCfg(gTestIS2.Mode, CfgInfo);


		/*	static int cnt =200;
			while(cnt --)
			{
				static aaa_tile_report_t act_tile;
				static img_aaa_stat_t aaa_stat_info;
				img_dsp_get_statistics(fd_iav, &aaa_stat_info, &act_tile);

			}*/
#endif
			//test_ituner_save(fd_iav, "/sdcard/test_ituner.txt");
			break;
		case DUMP_SECTION:
			idsp_dump_bin(fd_iav, sec_id);
			break;
		case SENSOR_CNTL:
			if(sensor_sht_row > 0) {
				struct vindev_shutter_row vsrc_shutter_row;
				vsrc_shutter_row.vsrc_id = 0;
				vsrc_shutter_row.shutter_row = sensor_sht_row;
				if(ioctl(fd_iav, IAV_IOC_VIN_SET_SHUTTER_ROW, &vsrc_shutter_row)<0)
					perror("IAV_IOC_VIN_SET_SHUTTER_ROW");
			}
			if(sensor_gain_index > 0) {
				struct vindev_agc_idx vsrc_agc_idx;
				vsrc_agc_idx.vsrc_id = 0;
				vsrc_agc_idx.agc_idx = sensor_gain_index;
				if(ioctl(fd_iav, IAV_IOC_VIN_SET_AGC_INDEX, &vsrc_agc_idx)<0)
					perror("IAV_IOC_VIN_SET_AGC_INDEX");
			}
			break;
		case FEED_RAW:

			loop_raw_cnt = loop_cycle*feed_raw_number;
			if(pthread_create(&thread_id, NULL, (void*)feed_loop, NULL)!=0) {
				printf("Fail to start feed_loop.\n");
				exit(-1);
			}
			if(enable_record) {
				if(pthread_create(&thread_id, NULL, (void*)rec_loop, NULL)!=0) {
					printf("Fail to start rec_loop.\n");
					exit(-1);
				}
			}
			printf("feed %d raw files in folder %s prefix %s\n", feed_raw_number, folder_name, prefix_name);

			int raw_width= 1280, raw_height=720;
			struct raw2enc_raw_feed_info feed_raw;
			struct iav_raw_enc_setup iav_feed_raw;

			raw_width = file_width;
			raw_height = file_height;
			int dpitch = ROUND_UP((raw_width << 1), 32);
			int raw_size = dpitch*raw_height;

			dest[0] = feed_addr;
			dest[1] = feed_addr + batch_num*raw_size;
			total_raw_cnt = 0;

			feed_raw.dpitch = dpitch;
			feed_raw.raw_size =raw_size;
			feed_raw.num_frames = batch_num;

			iav_feed_raw.pitch =dpitch;
			iav_feed_raw.raw_daddr_offset =0x500000;
			iav_feed_raw.raw_frame_size =raw_size;
			iav_feed_raw.raw_frame_num =batch_num;

			int idx = 0;
			sem_post(&feed_sem);
			if(enable_record)
				sem_post(&rec_sem);
			do {
				//while(total_raw_cnt < feed_raw_number) {
				while(total_raw_cnt < loop_raw_cnt) {
					//printf("wait for data ready, cnt %d\n", total_raw_cnt);
					sem_wait(&feed_ready_sem);
					sem_post(&feed_sem);
					//printf("data ready in %p\n", dest[idx]);
					feed_raw.daddr_offset  = ((u32)dest[idx] -(u32)ik_start_addr);
					//printf("feed_raw.daddr_offset =%x\n",feed_raw.daddr_offset);
					if (ioctl(fd_iav, IAV_IOC_IMG_FEED_RAW_NI, &feed_raw) < 0)
						printf("IAV_IOC_IMG_FEED_RAW_NI error\n");
					if (ioctl(fd_iav, IAV_IOC_SET_RAW_ENCODE, &iav_feed_raw) < 0)
						printf("IAV_IOC_SET_RAW_ENCODE error\n");
					idx ^= 1;
					//printf("data fired\n");
					if (ioctl(fd_iav, IAV_IOC_IMG_WAIT_RAW2ENC_NI) < 0)
						printf("IAV_IOC_IMG_WAIT_RAW2ENC_NI error\n");
					//printf("raw processed\n");
				}
				sem_wait(&feed_ready_sem);
				//printf("final data ready in %p\n", dest[idx]);
				feed_raw.daddr_offset= (u32)((u32)dest[idx] -(u32)ik_start_addr);
				if (ioctl(fd_iav, IAV_IOC_IMG_FEED_RAW_NI, &feed_raw) < 0)
					printf("IAV_IOC_IMG_FEED_RAW_NI error\n");
				if (ioctl(fd_iav, IAV_IOC_IMG_WAIT_RAW2ENC_NI) < 0)
					printf("IAV_IOC_IMG_WAIT_RAW2ENC_NI error\n");
				printf("final raw processed\n");

			}while(0);
//			if(enable_record)
//				system("test_encode -A -h720p -s");
			break;
		case DUMP_DEBUG: {
			int i;
			u32 cfg_start_addr_tmp = 0;
			printf("dump debug section to %s\n", folder_name);

			for (i=0; i<3; i++)
			{
			cfg_start_addr_tmp = (u32)cfg_start_addr+ (i*0x400);
			a12_low_iso_param_t* l_cfg = (a12_low_iso_param_t*)cfg_start_addr_tmp;

			// break if ucode doesn't write debug data
			if (l_cfg->share.debug_addr[0] == 0xffffffff ||l_cfg->share.debug_addr[1] == 0xffffffff || l_cfg->share.debug_config_addr == 0xffffffff)
				break;

			printf("sec %d, mem 0x%.8x\n", i, cfg_start_addr_tmp);
			printf("get debug step %d mode %d\n", l_cfg->share.debug_step_id, l_cfg->share.debug_mode);
			printf("debug cfg_addr 0x%x debug_addr 0x%x 0x%x\n", l_cfg->share.debug_config_addr,
									l_cfg->share.debug_addr[0], l_cfg->share.debug_addr[1]);
			printf("pitch %d %d width %d %d height %d %d\n", l_cfg->share.debug_pitch[0], l_cfg->share.debug_pitch[1],
									l_cfg->share.debug_width[0], l_cfg->share.debug_width[1],
									l_cfg->share.debug_height[0], l_cfg->share.debug_height[1]);

			int y_size = l_cfg->share.debug_pitch[0]*l_cfg->share.debug_height[0]; //l_cfg->share.debug_width[0]*l_cfg->share.debug_height[0];
			u32 y_src = l_cfg->share.debug_addr[0];
			int uv_size = l_cfg->share.debug_pitch[1]*l_cfg->share.debug_height[1]; //l_cfg->share.debug_width[1]*l_cfg->share.debug_height[1];
			u32 uv_src = l_cfg->share.debug_addr[1];
			u32 debug_cfg_src = l_cfg->share.debug_config_addr;
			int debug_cfg_size = 150*1024;

			char fn[64], shell_cmd[128];
			if(strlen(folder_name)==0)
				sprintf(folder_name, "/mnt/debug");
			sprintf(shell_cmd, "mkdir -p %s", folder_name);
			system(shell_cmd);

			if(debug_cfg_src != 0) {
				sprintf(fn, "frm%d_step%d_mode%d_cfg.bin", l_cfg->share.debug_pic_num, l_cfg->share.debug_step_id, l_cfg->share.debug_mode);
				sprintf(shell_cmd, "amba_debug -r 0x%x -s 0x%x -f %s/%s", debug_cfg_src, debug_cfg_size, folder_name, fn);
				system(shell_cmd);
			}
			if(y_src != 0) {
				sprintf(fn, "frm%d_step%d_mode%d_w%d_h%d.y", l_cfg->share.debug_pic_num, l_cfg->share.debug_step_id, l_cfg->share.debug_mode,
								l_cfg->share.debug_width[0], l_cfg->share.debug_height[0]);
				sprintf(shell_cmd, "amba_debug -r 0x%x -s 0x%x -f %s/%s", y_src, y_size, folder_name, fn);
				system(shell_cmd);
			}
			if(uv_src != 0) {
				sprintf(fn, "frm%d_step%d_mode%d_w%d_h%d.uv", l_cfg->share.debug_pic_num, l_cfg->share.debug_step_id, l_cfg->share.debug_mode,
								l_cfg->share.debug_width[1], l_cfg->share.debug_height[1]);
				sprintf(shell_cmd, "amba_debug -r 0x%x -s 0x%x -f %s/%s", uv_src, uv_size, folder_name, fn);
				system(shell_cmd);
			}

		}
		}
			break;
		case SLAVE_MODE:
			{
				int socket_fd, client_fd;

				int port = 3000;
				socklen_t client_size;

				socket_fd = creat_socket_server(htons(port), htonl(INADDR_ANY));
				if(socket_fd<0) return -1;

				client_size = sizeof(client);
				do {
					client_fd = accept(socket_fd, (struct sockaddr*)&client, &client_size);
					if(client_fd<0) {
						perror("accpet");
						printf("errno %d\n", errno);
					}
				}while(client_fd<0);
				printf("connected to %s:%u\n", inet_ntoa(client.sin_addr), ntohs(client.sin_port));
				printf("Numeric: %u\n", ntohl(client.sin_addr.s_addr));

				while(1) {
					int bytes;//, i;
					do {
						bytes = recv(client_fd, (void*)recv_buf, 128, MSG_WAITALL);
						if(bytes<=0) {
							printf("recv errno %d\n", errno);
							switch(errno){
							/*case EAGAIN:
								printf("restart recv\n");
								if((eth_link&0x1) == 0) {
									do {
										client_fd = accept(socket_fd, (struct sockaddr*)&client, &client_size);
										if(client_fd<0) {
											printf("accept errno %d\n", errno);
										}
									}while(client_fd<0);
									printf("EAGAIN connected to %s:%u\n", inet_ntoa(client.sin_addr), ntohs(client.sin_port));
									printf("Numeric: %u\n", ntohl(client.sin_addr.s_addr));
									//sprintf(snd_buf, "re-connected to A5s from link down, 3A loop running");
									//send(client_fd, snd_buf, 128, MSG_WAITALL);
								}
								break;*/
							case ECONNRESET:
								close(client_fd);
								printf("restart accept\n");
								do {
									client_fd = accept(socket_fd, (struct sockaddr*)&client, &client_size);
									if(client_fd<0) {
										printf("accept errno %d\n", errno);
									}
								}while(client_fd<0);
								printf("ECONNRESET connected to %s:%u\n", inet_ntoa(client.sin_addr), ntohs(client.sin_port));
								printf("Numeric: %u\n", ntohl(client.sin_addr.s_addr));
								//sprintf(snd_buf, "re-connected to A5s from socket reset, 3A loop running");
								//send(client_fd, snd_buf, 128, MSG_WAITALL);

								break;
							case EAGAIN:
							default:
								break;
							}
						}
					}while(bytes<=0);
					printf("cmd is %s\n", recv_buf);
					process_cmd(recv_buf);
				}
			}
			break;
		case TEST_MODE:
{
		#define FILE_NUM (20)
		int count = 0;
		int debug_step = 0,debug_mode = 0,debug_pic_num;
		a12_low_iso_param_t* l_cfg = 0;
		char* file_name[FILE_NUM] = {
			"/sdcard/s2l_liso/regs_and_paths_with_invisibleRUN_Vid25.txt",
			"/sdcard/s2l_liso/regs_and_paths_with_invisibleRUN_255.txt",
			"/sdcard/s2l_liso/regs_and_paths_with_invisibleRUN_Vid25.txt",
			"/sdcard/s2l_liso/regs_and_paths_with_invisibleRUN_255.txt",
			"/sdcard/s2l_liso/regs_and_paths_with_invisibleRUN_Vid25.txt",
			"/sdcard/s2l_liso/regs_and_paths_with_invisibleRUN_255.txt",
			"/sdcard/s2l_liso/regs_and_paths_with_invisibleRUN_Vid25.txt",
			"/sdcard/s2l_liso/regs_and_paths_with_invisibleRUN_255.txt",
			"/sdcard/s2l_liso/regs_and_paths_with_invisibleRUN_Vid25.txt",
			"/sdcard/s2l_liso/regs_and_paths_with_invisibleRUN_255.txt",
			"/sdcard/s2l_liso/regs_and_paths_with_invisibleRUN_Vid25.txt",
			"/sdcard/s2l_liso/regs_and_paths_with_invisibleRUN_255.txt",
			"/sdcard/s2l_liso/regs_and_paths_with_invisibleRUN_Vid25.txt",
			"/sdcard/s2l_liso/regs_and_paths_with_invisibleRUN_255.txt",
			"/sdcard/s2l_liso/regs_and_paths_with_invisibleRUN_Vid25.txt",
			"/sdcard/s2l_liso/regs_and_paths_with_invisibleRUN_255.txt",
			"/sdcard/s2l_liso/regs_and_paths_with_invisibleRUN_Vid25.txt",
			"/sdcard/s2l_liso/regs_and_paths_with_invisibleRUN_255.txt",
			"/sdcard/s2l_liso/regs_and_paths_with_invisibleRUN_Vid25.txt",
			"/sdcard/s2l_liso/regs_and_paths_with_invisibleRUN_255.txt"
		};

		test_is2_init(ik_start_addr);

		test_ituner(fd_iav, file_name[count]);//count = 0
		gTestIS2.Mode.ConfigId = CfgInfo.CfgId = count%2; // 0
		amba_img_dsp_post_exe_cfg(fd_iav, &gTestIS2.Mode, AMBA_DSP_IMG_CFG_EXE_PARTIALCOPY, 1);
		//AmbaDSP_ImgLowIsoPrintCfg(&gTestIS2.Mode, CfgInfo);

		printf("###CfgInfo.CfgId = %d\n",CfgInfo.CfgId);
		amba_img_dsp_get_liso_cfg(&CfgInfo, (void*)&l_cfg);

		//printf("###get cfg addr outside %p \n", l_cfg);

		gTestIS2.Mode.ConfigId = CfgInfo.CfgId = (++count)%2; // 1
		amba_img_dsp_post_exe_cfg(fd_iav, &gTestIS2.Mode, AMBA_DSP_IMG_CFG_EXE_FULLCOPY, 0);
		//AmbaDSP_ImgLowIsoPrintCfg(&gTestIS2.Mode, CfgInfo);

		printf("\n\n");

		while(1){

		//getchar();
		printf("set next case %s debug:\n", file_name[count]);
		printf("[step] [mode] [pic_num]\n");

		scanf("%d %d %d", &debug_step, &debug_mode, &debug_pic_num);
		debug.Step = debug_step;
		debug.Mode = debug_mode;
		debug.ChannelID = 0;
		debug.TileX = 0;
		debug.TileY = 0;
		debug.PicNum = debug_pic_num;

		printf("###debug.Step= %d debug.Mode= %d\n",debug.Step , debug.Mode);

		test_ituner(fd_iav, file_name[count]);

		gTestIS2.Mode.ConfigId = CfgInfo.CfgId = count % 2;
		printf("load ituner file %s count %d cfg id %d\n", file_name[count], count, gTestIS2.Mode.ConfigId);

		amba_img_dsp_set_debug_mode(&gTestIS2.Mode, &debug);
		amba_img_dsp_post_exe_cfg(fd_iav, &gTestIS2.Mode, AMBA_DSP_IMG_CFG_EXE_PARTIALCOPY, 0);
		if(debug.Step != 0){
			AmbaDSP_ImgLowIsoPrintCfg(CfgInfo);
			AmbaDSP_ImgLowIsoDumpCfg(CfgInfo, "/mnt");
		}

		amba_img_dsp_get_liso_cfg(&CfgInfo, (void*)&l_cfg);

		printf("get cfg addr outside %p debug %d %d\n", l_cfg, l_cfg->share.debug_step_id, l_cfg->share.debug_mode);
		sleep(1);

		if(debug.Step == 0 && count < (FILE_NUM-1)){
			printf("!!!!!copy config %d to config %d\n", count%2 , (count+1)%2);
			gTestIS2.Mode.ConfigId = CfgInfo.CfgId = (++count)%2;
			amba_img_dsp_post_exe_cfg(fd_iav, &gTestIS2.Mode, AMBA_DSP_IMG_CFG_EXE_FULLCOPY, 0);
		}else{
			printf("idsp dump step %d mode %d complete\n",debug.Step, debug.Mode);
			break;
		}
		printf("\n\n");
	}
}
	break;
	case CONVERT_MODE:
			printf("convert ituner file %s\n", file_name);
			test_is2_init(ik_start_addr);
			test_ituner(fd_iav, file_name);
			amba_img_dsp_post_exe_cfg(fd_iav, &gTestIS2.Mode, 2, 1);

			char adj_fn[128];
			char tmp_str[1024];
			int pos;
			for(pos=0; pos<strlen(file_name); pos++){
				if(file_name[pos] == '.')
					break;
			}
			memset(tmp_str, 0, sizeof(tmp_str));
			memcpy(tmp_str, file_name, pos);
			sprintf(adj_fn, "%s_adj.c", tmp_str);
			printf("write to %s\n", adj_fn);
			FILE* file = fopen(adj_fn, "w");
			memset(tmp_str, 0, sizeof(tmp_str));
			{
				int i=0;
				amba_img_dsp_black_correction_t blc;
				amba_img_dsp_get_static_black_level(&gTestIS2.Mode,&blc);
				sprintf(tmp_str, "ADJ_BLC\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				sprintf(tmp_str, ".param[N] = {{%d, %d, %d, %d,  %d, %d, %d, %d}},\r\n", blc.BlackR,blc.BlackGr,
												blc.BlackGb, blc.BlackB,
												blc.BlackR,blc.BlackGr,
												blc.BlackGb, blc.BlackB);
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				sprintf(tmp_str, "\r\nADJ_ANTIALIASING\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);

                amba_img_dsp_anti_aliasing_t        AntiAliasing;
				amba_img_dsp_get_anti_aliasing(&gTestIS2.Mode,&AntiAliasing);
				sprintf(tmp_str, ".param[N] =  {{%d,   %d,   %d}},\r\n", AntiAliasing.Enb, AntiAliasing.Thresh, AntiAliasing.LogFractionalCorrect);

				fwrite(tmp_str, strlen(tmp_str), 1, file);

				sprintf(tmp_str, "\r\nADJ_MO_ANTIALIASING\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);

                amba_img_dsp_anti_aliasing_t        MoAntiAliasing;
				amba_img_dsp_get_mo_anti_aliasing(&gTestIS2.Mode,&MoAntiAliasing);
				sprintf(tmp_str, ".param[N] =  {{%d,   %d,   %d}},\r\n", MoAntiAliasing.Enb, MoAntiAliasing.Thresh, MoAntiAliasing.LogFractionalCorrect);

				fwrite(tmp_str, strlen(tmp_str), 1, file);

				sprintf(tmp_str, "\r\nADJ_GRGB_MISMATCH\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				amba_img_dsp_gbgr_mismatch_t mis;
				amba_img_dsp_get_gbgr_mismatch(&gTestIS2.Mode, &mis);
				sprintf(tmp_str, ".param[N] =  {{%d,   %d,   %d,   %d}},\r\n", mis.NarrowEnable, mis.WideEnable,mis.WideSafety, mis.WideThresh);
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				sprintf(tmp_str, "\r\nADJ_MO_GRGB_MISMATCH\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				amba_img_dsp_gbgr_mismatch_t Momis;
				amba_img_dsp_get_mo_gbgr_mismatch(&gTestIS2.Mode, &Momis);
				sprintf(tmp_str, ".param[N] =  {{%d,   %d,   %d,   %d}},\r\n", Momis.NarrowEnable, Momis.WideEnable,Momis.WideSafety, Momis.WideThresh);
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				//ADJ_DPC
				sprintf(tmp_str, "\r\nADJ_DPC\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				amba_img_dsp_dbp_correction_t dpc;
				amba_img_dsp_get_dynamic_bad_pixel_correction(&gTestIS2.Mode, &dpc);
				sprintf(tmp_str, ".param[N] =  {{%d,  %d,  %d,  %d}},\r\n", dpc.Enb, dpc.HotPixelStrength, dpc.DarkPixelStrength, dpc.CorrectionMethod);
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				sprintf(tmp_str, "\r\nADJ_MO_DPC\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				amba_img_dsp_dbp_correction_t Modpc;
				amba_img_dsp_get_mo_dynamic_bad_pixel_correction(&gTestIS2.Mode, &Modpc);
				sprintf(tmp_str, ".param[N] =  {{%d,  %d,  %d,  %d}},\r\n", Modpc.Enb, Modpc.HotPixelStrength, Modpc.DarkPixelStrength, Modpc.CorrectionMethod);
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				//ADJ_CFANF_LOW
				sprintf(tmp_str, "\r\nADJ_CFANF_LOW\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				amba_img_dsp_cfa_noise_filter_t cfa;
				amba_img_dsp_get_cfa_noise_filter(&gTestIS2.Mode, &cfa);
				sprintf(tmp_str, ".param[N]  = {{%d,   %d,   %d,   %d,   %d,  %d,  %d, %d, %d, %d, %d, %d, %d,  %d, %d, %d, %d,   %d,}},\r\n",
					cfa.Enb, cfa.NoiseLevel[0], cfa.NoiseLevel[1], cfa.NoiseLevel[2], cfa.OriginalBlendStr[0], cfa.OriginalBlendStr[1], cfa.OriginalBlendStr[2],
					cfa.ExtentRegular[0], cfa.ExtentRegular[1], cfa.ExtentRegular[2], cfa.ExtentFine[0], cfa.ExtentFine[1], cfa.ExtentFine[2],
					cfa.StrengthFine[0], cfa.StrengthFine[1], cfa.StrengthFine[2], cfa.SelectivityRegular, cfa.SelectivityFine);
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				sprintf(tmp_str, "\r\nADJ_MO_CFANF_LOW\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				amba_img_dsp_cfa_noise_filter_t Mocfa;
				amba_img_dsp_get_mo_cfa_noise_filter(&gTestIS2.Mode, &Mocfa);
				sprintf(tmp_str, ".param[N]  = {{%d,   %d,   %d,   %d,   %d,  %d,  %d, %d, %d, %d, %d, %d, %d,  %d, %d, %d, %d,   %d,}},\r\n",
					Mocfa.Enb, Mocfa.NoiseLevel[0], Mocfa.NoiseLevel[1], Mocfa.NoiseLevel[2], Mocfa.OriginalBlendStr[0], Mocfa.OriginalBlendStr[1], Mocfa.OriginalBlendStr[2],
					Mocfa.ExtentRegular[0], Mocfa.ExtentRegular[1], Mocfa.ExtentRegular[2], Mocfa.ExtentFine[0], Mocfa.ExtentFine[1], Mocfa.ExtentFine[2],
					Mocfa.StrengthFine[0], Mocfa.StrengthFine[1], Mocfa.StrengthFine[2], Mocfa.SelectivityRegular, Mocfa.SelectivityFine);
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				//ADJ_DEMOSAIC
				sprintf(tmp_str, "\r\nADJ_DEMOSAIC\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				amba_img_dsp_demosaic_t demosaic;
				amba_img_dsp_get_demosaic(&gTestIS2.Mode, &demosaic);
				sprintf(tmp_str, ".param[N] =  {{%d, %d, %d, %d}},\r\n",
					demosaic.ActivityThresh, demosaic.ActivityDifferenceThresh, demosaic.GradClipThresh, demosaic.GradNoiseThresh);
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				sprintf(tmp_str, "\r\nADJ_MO_DEMOSAIC\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				amba_img_dsp_demosaic_t Modemosaic;
				amba_img_dsp_get_mo_demosaic(&gTestIS2.Mode, &Modemosaic);
				sprintf(tmp_str, ".param[N] =  {{%d, %d, %d, %d}},\r\n",
					Modemosaic.ActivityThresh, Modemosaic.ActivityDifferenceThresh, Modemosaic.GradClipThresh, Modemosaic.GradNoiseThresh);
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				//ADJ_TONE
				sprintf(tmp_str, "\r\nADJ_TONE\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				amba_img_dsp_tone_curve_t tone;
				amba_img_dsp_get_tone_curve(&gTestIS2.Mode, &tone);
				sprintf(tmp_str, ".tbl0 = {\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				for(i=0; i<256; i++) {
					if(!(i%32) && i!=0){
						sprintf(tmp_str, "\r\n");
						fwrite(tmp_str, strlen(tmp_str), 1, file);
					}
					sprintf(tmp_str, "%4d,", tone.ToneCurveRed[i]);
					fwrite(tmp_str, strlen(tmp_str), 1, file);
				}
				sprintf(tmp_str, "\r\n},\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				sprintf(tmp_str, ".tbl1 = {\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				for(i=0; i<256; i++) {
					if(!(i%32) && i!=0){
						sprintf(tmp_str, "\r\n");
						fwrite(tmp_str, strlen(tmp_str), 1, file);
					}
					sprintf(tmp_str, "%4d,", tone.ToneCurveGreen[i]);
					fwrite(tmp_str, strlen(tmp_str), 1, file);
				}
				sprintf(tmp_str, "\r\n},\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				sprintf(tmp_str, ".tbl2 = {\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				for(i=0; i<256; i++) {
					if(!(i%32) && i!=0){
						sprintf(tmp_str, "\r\n");
						fwrite(tmp_str, strlen(tmp_str), 1, file);
					}
					sprintf(tmp_str, "%4d,", tone.ToneCurveBlue[i]);
					fwrite(tmp_str, strlen(tmp_str), 1, file);
				}
				sprintf(tmp_str, "\r\n},\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);


				sprintf(tmp_str, "\r\nADJ_CHROMA_SCALE\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				amba_img_dsp_chroma_scale_t cs;
				amba_img_dsp_get_chroma_scale(&gTestIS2.Mode, &cs);
				sprintf(tmp_str, ".param[N] =  {{%d, }},\r\n",cs.Enb);
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				sprintf(tmp_str, ".tbl0 = {\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				for(i=0; i<128; i++) {
					if(!(i%32) && i!=0){
						sprintf(tmp_str, "\r\n");
						fwrite(tmp_str, strlen(tmp_str), 1, file);
					}
					sprintf(tmp_str, "%4d,", cs.GainCurve[i]);
					fwrite(tmp_str, strlen(tmp_str), 1, file);
				}
				sprintf(tmp_str, "\r\n},\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);


				sprintf(tmp_str, "\r\nADJ_CHROMA_MEDIAN\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				amba_img_dsp_chroma_median_filter_t cm;
				amba_img_dsp_get_chroma_median_filter(&gTestIS2.Mode, &cm);
				sprintf(tmp_str, ".param[N] =  {{%d, %d, %d, %d, %d, %d, %d,}},\r\n",
					cm.Enable, cm.CbAdaptiveStrength, cm.CrAdaptiveStrength, cm.CbNonAdaptiveStrength, cm.CrNonAdaptiveStrength,
					cm.CbAdaptiveAmount, cm.CrAdaptiveAmount);
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				sprintf(tmp_str, "\r\nADJ_MO_CHROMA_MEDIAN\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				amba_img_dsp_chroma_median_filter_t Mocm;
				amba_img_dsp_get_mo_chroma_median_filter(&gTestIS2.Mode, &Mocm);
				sprintf(tmp_str, ".param[N] =  {{%d, %d, %d, %d, %d, %d, %d,}},\r\n",
					Mocm.Enable, Mocm.CbAdaptiveStrength, Mocm.CrAdaptiveStrength, Mocm.CbNonAdaptiveStrength, Mocm.CrNonAdaptiveStrength,
					Mocm.CbAdaptiveAmount, Mocm.CrAdaptiveAmount);
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				//ADJ_CHROMANF
				sprintf(tmp_str, "\r\nADJ_CHROMANF\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				amba_img_dsp_chroma_filter_t cf;
				amba_img_dsp_get_chroma_filter(&gTestIS2.Mode, &cf);
				sprintf(tmp_str, ".param[N] =  {{%d, %d, %d, %d, %d, %d,}},\r\n",
					cf.Enable, cf.NoiseLevelCb, cf.NoiseLevelCr, cf.OriginalBlendStrengthCb, cf.OriginalBlendStrengthCr, cf.Radius);
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				sprintf(tmp_str, "\r\nADJ_MO_CHROMANF\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				amba_img_dsp_chroma_filter_t Mocf;
				amba_img_dsp_get_mo_chroma_filter(&gTestIS2.Mode, &Mocf);
				sprintf(tmp_str, ".param[N] =  {{%d, %d, %d, %d, %d, %d,}},\r\n",
					Mocf.Enable, Mocf.NoiseLevelCb, Mocf.NoiseLevelCr, Mocf.OriginalBlendStrengthCb, Mocf.OriginalBlendStrengthCr, Mocf.Radius);
				fwrite(tmp_str, strlen(tmp_str), 1, file);


				//ADJ_1STMODE_SEL
				sprintf(tmp_str, "\r\nADJ_1STMODE_SEL\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				amba_img_dsp_liso_process_select_t sel;
				amba_img_dsp_get_luma_processing_mode(&gTestIS2.Mode, &sel);
				sprintf(tmp_str, ".param[N] =  {{%d,}},\r\n", sel.UseSharpenNotAsf);
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				sprintf(tmp_str, "\r\nADJ_MO_MODE_SEL\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				amba_img_dsp_liso_process_select_t Mosel;
				amba_img_dsp_get_mo_luma_processing_mode(&gTestIS2.Mode, &Mosel);
				sprintf(tmp_str, ".param[N] =  {{%d,}},\r\n", Mosel.UseSharpenNotAsf);
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				//ADJ_ASF
				sprintf(tmp_str, "\r\nADJ_ASF\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				amba_img_dsp_asf_info_t asf;
				amba_img_dsp_get_advance_spatial_filter(&gTestIS2.Mode, &asf);
				sprintf(tmp_str, ".param[N] =  {{%d,  %d,   %d,   %d, %d,   %d,     %d, %d,    %d,     %d,     %d,   %d,    %d,        %d,       %d,     %d,    %d,  %d,      %d,   %d,  %d,  %d,       %d,    %d,     %d,   %d,     %d,   %d,  %d,    %d,     %d,    %d,       %d,}},\r\n",
					asf.Enable, asf.Fir.Specify, asf.Fir.StrengthIso, asf.Fir.StrengthDir, asf.Fir.EdgeThresh, asf.Fir.WideEdgeDetect, asf.DirectionalDecideT0, asf.DirectionalDecideT1,
					asf.Adapt.AlphaMinUp, asf.Adapt.AlphaMaxUp, asf.Adapt.T0Up, asf.Adapt.T1Up, asf.Adapt.AlphaMinDown, asf.Adapt.AlphaMaxDown, asf.Adapt.T0Down, asf.Adapt.T1Down,
					asf.LevelStrAdjust.Low, asf.LevelStrAdjust.LowDelta, asf.LevelStrAdjust.LowStrength, asf.LevelStrAdjust.MidStrength, asf.LevelStrAdjust.High, asf.LevelStrAdjust.HighDelta, asf.LevelStrAdjust.HighStrength,
					asf.T0T1Div.Low, asf.T0T1Div.LowDelta, asf.T0T1Div.LowStrength, asf.T0T1Div.MidStrength, asf.T0T1Div.High, asf.T0T1Div.HighDelta, asf.T0T1Div.HighStrength,
					asf.MaxChangeNotT0T1Alpha,asf.MaxChangeUp, asf.MaxChangeDown);
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				sprintf(tmp_str, ".tbl0 = {//PerDirFirIsoStrengths\r\n{{");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				for(i=0; i<9; i++) {
					if(!(i%32) && i!=0){
						sprintf(tmp_str, "\r\n");
						fwrite(tmp_str, strlen(tmp_str), 1, file);
					}
					sprintf(tmp_str, "%2d,", asf.Fir.PerDirFirIsoStrengths[i]);
					fwrite(tmp_str, strlen(tmp_str), 1, file);
				}
				sprintf(tmp_str, "},},\r\n},\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				sprintf(tmp_str, ".tbl1 = {//PerDirFirDirStrengths\r\n{{");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				for(i=0; i<9; i++) {
					if(!(i%32) && i!=0){
						sprintf(tmp_str, "\r\n");
						fwrite(tmp_str, strlen(tmp_str), 1, file);
					}
					sprintf(tmp_str, "%2d,", asf.Fir.PerDirFirDirStrengths[i]);
					fwrite(tmp_str, strlen(tmp_str), 1, file);
				}
				sprintf(tmp_str, "},},\r\n},\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				sprintf(tmp_str, ".tbl2 = {//PerDirFirDirAmounts\r\n{{");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				for(i=0; i<9; i++) {
					if(!(i%32) && i!=0){
						sprintf(tmp_str, "\r\n");
						fwrite(tmp_str, strlen(tmp_str), 1, file);
					}
					sprintf(tmp_str, "%2d,", asf.Fir.PerDirFirDirAmounts[i]);
					fwrite(tmp_str, strlen(tmp_str), 1, file);
				}
				sprintf(tmp_str, "},},\r\n},\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				sprintf(tmp_str, ".tbl3 = {//Coefs[9][25]\r\n{{");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				int j;
				for(j=0; j<9; j++) {
					for(i=0; i<25; i++) {
						sprintf(tmp_str, "%2d,", asf.Fir.Coefs[j][i]);
						fwrite(tmp_str, strlen(tmp_str), 1, file);
					}
					sprintf(tmp_str, "\r\n");
					fwrite(tmp_str, strlen(tmp_str), 1, file);
				}
				sprintf(tmp_str, "},},\r\n},\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				sprintf(tmp_str, "\r\nADJ_MO_ASF\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				amba_img_dsp_asf_info_t Moasf;
				amba_img_dsp_get_mo_advance_spatial_filter(&gTestIS2.Mode, &Moasf);
				sprintf(tmp_str, ".param[N] =  {{%d,  %d,   %d,   %d, %d,   %d,     %d, %d,    %d,     %d,     %d,   %d,    %d,        %d,       %d,     %d,    %d,  %d,      %d,   %d,  %d,  %d,       %d,    %d,     %d,   %d,     %d,   %d,  %d,    %d,     %d,    %d,       %d,}},\r\n",
					Moasf.Enable, Moasf.Fir.Specify, Moasf.Fir.StrengthIso, Moasf.Fir.StrengthDir, Moasf.Fir.EdgeThresh, Moasf.Fir.WideEdgeDetect, Moasf.DirectionalDecideT0, Moasf.DirectionalDecideT1,
					Moasf.Adapt.AlphaMinUp, Moasf.Adapt.AlphaMaxUp, Moasf.Adapt.T0Up, Moasf.Adapt.T1Up, Moasf.Adapt.AlphaMinDown, Moasf.Adapt.AlphaMaxDown, Moasf.Adapt.T0Down, Moasf.Adapt.T1Down,
					Moasf.LevelStrAdjust.Low, Moasf.LevelStrAdjust.LowDelta, Moasf.LevelStrAdjust.LowStrength, Moasf.LevelStrAdjust.MidStrength, Moasf.LevelStrAdjust.High, Moasf.LevelStrAdjust.HighDelta, Moasf.LevelStrAdjust.HighStrength,
					Moasf.T0T1Div.Low, Moasf.T0T1Div.LowDelta, Moasf.T0T1Div.LowStrength, Moasf.T0T1Div.MidStrength, Moasf.T0T1Div.High, Moasf.T0T1Div.HighDelta, Moasf.T0T1Div.HighStrength,
					Moasf.MaxChangeNotT0T1Alpha,Moasf.MaxChangeUp, Moasf.MaxChangeDown);
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				sprintf(tmp_str, ".tbl0 = {//PerDirFirIsoStrengths\r\n{{");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				for(i=0; i<9; i++) {
					if(!(i%32) && i!=0){
						sprintf(tmp_str, "\r\n");
						fwrite(tmp_str, strlen(tmp_str), 1, file);
					}
					sprintf(tmp_str, "%2d,", Moasf.Fir.PerDirFirIsoStrengths[i]);
					fwrite(tmp_str, strlen(tmp_str), 1, file);
				}
				sprintf(tmp_str, "},},\r\n},\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				sprintf(tmp_str, ".tbl1 = {//PerDirFirDirStrengths\r\n{{");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				for(i=0; i<9; i++) {
					if(!(i%32) && i!=0){
						sprintf(tmp_str, "\r\n");
						fwrite(tmp_str, strlen(tmp_str), 1, file);
					}
					sprintf(tmp_str, "%2d,", Moasf.Fir.PerDirFirDirStrengths[i]);
					fwrite(tmp_str, strlen(tmp_str), 1, file);
				}
				sprintf(tmp_str, "},},\r\n},\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				sprintf(tmp_str, ".tbl2 = {//PerDirFirDirAmounts\r\n{{");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				for(i=0; i<9; i++) {
					if(!(i%32) && i!=0){
						sprintf(tmp_str, "\r\n");
						fwrite(tmp_str, strlen(tmp_str), 1, file);
					}
					sprintf(tmp_str, "%2d,", Moasf.Fir.PerDirFirDirAmounts[i]);
					fwrite(tmp_str, strlen(tmp_str), 1, file);
				}
				sprintf(tmp_str, "},},\r\n},\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				sprintf(tmp_str, ".tbl3 = {//Coefs[9][25]\r\n{{");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				for(j=0; j<9; j++) {
					for(i=0; i<25; i++) {
						sprintf(tmp_str, "%2d,", Moasf.Fir.Coefs[j][i]);
						fwrite(tmp_str, strlen(tmp_str), 1, file);
					}
					sprintf(tmp_str, "\r\n");
					fwrite(tmp_str, strlen(tmp_str), 1, file);
				}
				sprintf(tmp_str, "},},\r\n},\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				//ADJ_1ST_SHPBOTH
				sprintf(tmp_str, "\r\nADJ_1ST_SHPBOTH\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				amba_img_dsp_sharpen_both_t sa_both;
				amba_img_dsp_get_1st_sharpen_noise_both(&gTestIS2.Mode, &sa_both);
				sprintf(tmp_str, ".param[N] =  {{%d,   %d,   %d,         %d,      %d,   %d,}},\r\n",
					sa_both.Enable, sa_both.Mode, sa_both.EdgeThresh, sa_both.WideEdgeDetect,
					sa_both.MaxChangeUp5x5, sa_both.MaxChangeDown5x5);
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				sprintf(tmp_str, "\r\nADJ_MO_SHPBOTH\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				amba_img_dsp_sharpen_both_t Mosa_both;
				amba_img_dsp_get_mo_sharpen_noise_both(&gTestIS2.Mode, &Mosa_both);
				sprintf(tmp_str, ".param[N] =  {{%d,   %d,   %d,         %d,      %d,   %d,}},\r\n",
					Mosa_both.Enable, Mosa_both.Mode, Mosa_both.EdgeThresh, Mosa_both.WideEdgeDetect,
					Mosa_both.MaxChangeUp5x5, Mosa_both.MaxChangeDown5x5);
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				//ADJ_1ST_SHPNOISE
				sprintf(tmp_str, "\r\nADJ_1ST_SHPNOISE\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				amba_img_dsp_sharpen_noise_t sa_noise;
				amba_img_dsp_get_1st_sharpen_noise_noise(&gTestIS2.Mode, &sa_noise);
				sprintf(tmp_str, ".param[N] =  {{%d,    %d,     %d,     %d,   %d,   %d,     %d,   %d,  %d,   %d,    %d,  %d, %d,     %d,    %d,	%d,	%d,	%d,	%d }},\r\n",
					sa_noise.MaxChangeUp, sa_noise.MaxChangeDown, sa_noise.SpatialFir.Specify, sa_noise.SpatialFir.StrengthIso, sa_noise.SpatialFir.StrengthDir,
					sa_noise.SpatialFir.EdgeThresh, sa_noise.SpatialFir.WideEdgeDetect,
					sa_noise.LevelStrAdjust.Low, sa_noise.LevelStrAdjust.LowDelta, sa_noise.LevelStrAdjust.LowStrength, sa_noise.LevelStrAdjust.MidStrength,
					sa_noise.LevelStrAdjust.High, sa_noise.LevelStrAdjust.HighDelta, sa_noise.LevelStrAdjust.HighStrength,
					sa_noise.LevelStrAdjustNotT0T1LevelBased,sa_noise.T0,sa_noise.T1,sa_noise.AlphaMin,sa_noise.AlphaMax);
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				sprintf(tmp_str, ".tbl0 = {//PerDirFirIsoStrengths\r\n{{");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				for(i=0; i<9; i++) {
					if(!(i%32) && i!=0){
						sprintf(tmp_str, "\r\n");
						fwrite(tmp_str, strlen(tmp_str), 1, file);
					}
					sprintf(tmp_str, "%2d,", sa_noise.SpatialFir.PerDirFirIsoStrengths[i]);
					fwrite(tmp_str, strlen(tmp_str), 1, file);
				}
				sprintf(tmp_str, "},},\r\n},\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				sprintf(tmp_str, ".tbl1 = {//PerDirFirDirStrengths\r\n{{");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				for(i=0; i<9; i++) {
					if(!(i%32) && i!=0){
						sprintf(tmp_str, "\r\n");
						fwrite(tmp_str, strlen(tmp_str), 1, file);
					}
					sprintf(tmp_str, "%2d,", sa_noise.SpatialFir.PerDirFirDirStrengths[i]);
					fwrite(tmp_str, strlen(tmp_str), 1, file);
				}
				sprintf(tmp_str, "},},\r\n},\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				sprintf(tmp_str, ".tbl2 = {//PerDirFirDirAmounts\r\n{{");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				for(i=0; i<9; i++) {
					if(!(i%32) && i!=0){
						sprintf(tmp_str, "\r\n");
						fwrite(tmp_str, strlen(tmp_str), 1, file);
					}
					sprintf(tmp_str, "%2d,", sa_noise.SpatialFir.PerDirFirDirAmounts[i]);
					fwrite(tmp_str, strlen(tmp_str), 1, file);
				}
				sprintf(tmp_str, "},},\r\n},\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				sprintf(tmp_str, ".tbl3 = {//Coefs[9][25]\r\n{{");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				for(j=0; j<9; j++) {
					for(i=0; i<25; i++) {
						sprintf(tmp_str, "%3d,", sa_noise.SpatialFir.Coefs[j][i]);
						fwrite(tmp_str, strlen(tmp_str), 1, file);
					}
					sprintf(tmp_str, "\r\n");
					fwrite(tmp_str, strlen(tmp_str), 1, file);
				}
				sprintf(tmp_str, "},},\r\n},\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				sprintf(tmp_str, "\r\nADJ_MO_SHPNOISE\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				amba_img_dsp_sharpen_noise_t Mosa_noise;
				amba_img_dsp_get_mo_sharpen_noise_noise(&gTestIS2.Mode, &Mosa_noise);
				sprintf(tmp_str, ".param[N] =  {{%d,    %d,     %d,     %d,   %d,   %d,     %d,   %d,  %d,   %d,    %d,  %d, %d,     %d,    %d,	%d,	%d,	%d,	%d }},\r\n",
					Mosa_noise.MaxChangeUp, Mosa_noise.MaxChangeDown, Mosa_noise.SpatialFir.Specify, Mosa_noise.SpatialFir.StrengthIso, Mosa_noise.SpatialFir.StrengthDir,
					Mosa_noise.SpatialFir.EdgeThresh, Mosa_noise.SpatialFir.WideEdgeDetect,
					Mosa_noise.LevelStrAdjust.Low, Mosa_noise.LevelStrAdjust.LowDelta, Mosa_noise.LevelStrAdjust.LowStrength, Mosa_noise.LevelStrAdjust.MidStrength,
					Mosa_noise.LevelStrAdjust.High, Mosa_noise.LevelStrAdjust.HighDelta, Mosa_noise.LevelStrAdjust.HighStrength,
					Mosa_noise.LevelStrAdjustNotT0T1LevelBased,Mosa_noise.T0,Mosa_noise.T1,Mosa_noise.AlphaMin,Mosa_noise.AlphaMax);
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				sprintf(tmp_str, ".tbl0 = {//PerDirFirIsoStrengths\r\n{{");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				for(i=0; i<9; i++) {
					if(!(i%32) && i!=0){
						sprintf(tmp_str, "\r\n");
						fwrite(tmp_str, strlen(tmp_str), 1, file);
					}
					sprintf(tmp_str, "%2d,", Mosa_noise.SpatialFir.PerDirFirIsoStrengths[i]);
					fwrite(tmp_str, strlen(tmp_str), 1, file);
				}
				sprintf(tmp_str, "},},\r\n},\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				sprintf(tmp_str, ".tbl1 = {//PerDirFirDirStrengths\r\n{{");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				for(i=0; i<9; i++) {
					if(!(i%32) && i!=0){
						sprintf(tmp_str, "\r\n");
						fwrite(tmp_str, strlen(tmp_str), 1, file);
					}
					sprintf(tmp_str, "%2d,", Mosa_noise.SpatialFir.PerDirFirDirStrengths[i]);
					fwrite(tmp_str, strlen(tmp_str), 1, file);
				}
				sprintf(tmp_str, "},},\r\n},\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				sprintf(tmp_str, ".tbl2 = {//PerDirFirDirAmounts\r\n{{");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				for(i=0; i<9; i++) {
					if(!(i%32) && i!=0){
						sprintf(tmp_str, "\r\n");
						fwrite(tmp_str, strlen(tmp_str), 1, file);
					}
					sprintf(tmp_str, "%2d,", Mosa_noise.SpatialFir.PerDirFirDirAmounts[i]);
					fwrite(tmp_str, strlen(tmp_str), 1, file);
				}
				sprintf(tmp_str, "},},\r\n},\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				sprintf(tmp_str, ".tbl3 = {//Coefs[9][25]\r\n{{");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				for(j=0; j<9; j++) {
					for(i=0; i<25; i++) {
						sprintf(tmp_str, "%3d,", Mosa_noise.SpatialFir.Coefs[j][i]);
						fwrite(tmp_str, strlen(tmp_str), 1, file);
					}
					sprintf(tmp_str, "\r\n");
					fwrite(tmp_str, strlen(tmp_str), 1, file);
				}
				sprintf(tmp_str, "},},\r\n},\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				//ADJ_1ST_SHPFIR
				sprintf(tmp_str, "\r\nADJ_1ST_SHPFIR\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				amba_img_dsp_fir_t sa_fir;
				amba_img_dsp_get_1st_sharpen_noise_sharpen_fir(&gTestIS2.Mode, &sa_fir);
				sprintf(tmp_str, ".param[N] =  {{%d,   %d,   %d,    %d,     %d,}},\r\n",
					sa_fir.Specify, sa_fir.StrengthIso, sa_fir.StrengthDir, sa_fir.EdgeThresh, sa_fir.WideEdgeDetect);
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				sprintf(tmp_str, ".tbl0 = {//PerDirFirIsoStrengths\r\n{{");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				for(i=0; i<9; i++) {
					if(!(i%32) && i!=0){
						sprintf(tmp_str, "\r\n");
						fwrite(tmp_str, strlen(tmp_str), 1, file);
					}
					sprintf(tmp_str, "%2d,", sa_fir.PerDirFirIsoStrengths[i]);
					fwrite(tmp_str, strlen(tmp_str), 1, file);
				}
				sprintf(tmp_str, "},},\r\n},\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				sprintf(tmp_str, ".tbl1 = {//PerDirFirDirStrengths\r\n{{");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				for(i=0; i<9; i++) {
					if(!(i%32) && i!=0){
						sprintf(tmp_str, "\r\n");
						fwrite(tmp_str, strlen(tmp_str), 1, file);
					}
					sprintf(tmp_str, "%2d,", sa_fir.PerDirFirDirStrengths[i]);
					fwrite(tmp_str, strlen(tmp_str), 1, file);
				}
				sprintf(tmp_str, "},},\r\n},\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				sprintf(tmp_str, ".tbl2 = {//PerDirFirDirAmounts\r\n{{");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				for(i=0; i<9; i++) {
					if(!(i%32) && i!=0){
						sprintf(tmp_str, "\r\n");
						fwrite(tmp_str, strlen(tmp_str), 1, file);
					}
					sprintf(tmp_str, "%2d,", sa_fir.PerDirFirDirAmounts[i]);
					fwrite(tmp_str, strlen(tmp_str), 1, file);
				}
				sprintf(tmp_str, "},},\r\n},\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				sprintf(tmp_str, ".tbl3 = {//Coefs[9][25]\r\n{{");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				for(j=0; j<9; j++) {
					for(i=0; i<25; i++) {
						sprintf(tmp_str, "%3d,", sa_fir.Coefs[j][i]);
						fwrite(tmp_str, strlen(tmp_str), 1, file);
					}
					sprintf(tmp_str, "\r\n");
					fwrite(tmp_str, strlen(tmp_str), 1, file);
				}
				sprintf(tmp_str, "},},\r\n},\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				sprintf(tmp_str, "\r\nADJ_MO_SHPFIR\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				amba_img_dsp_fir_t Mosa_fir;
				amba_img_dsp_get_mo_sharpen_noise_sharpen_fir(&gTestIS2.Mode, &Mosa_fir);
				sprintf(tmp_str, ".param[N] =  {{%d,   %d,   %d,    %d,     %d,}},\r\n",
					Mosa_fir.Specify, Mosa_fir.StrengthIso, Mosa_fir.StrengthDir, Mosa_fir.EdgeThresh, Mosa_fir.WideEdgeDetect);
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				sprintf(tmp_str, ".tbl0 = {//PerDirFirIsoStrengths\r\n{{");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				for(i=0; i<9; i++) {
					if(!(i%32) && i!=0){
						sprintf(tmp_str, "\r\n");
						fwrite(tmp_str, strlen(tmp_str), 1, file);
					}
					sprintf(tmp_str, "%2d,", Mosa_fir.PerDirFirIsoStrengths[i]);
					fwrite(tmp_str, strlen(tmp_str), 1, file);
				}
				sprintf(tmp_str, "},},\r\n},\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				sprintf(tmp_str, ".tbl1 = {//PerDirFirDirStrengths\r\n{{");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				for(i=0; i<9; i++) {
					if(!(i%32) && i!=0){
						sprintf(tmp_str, "\r\n");
						fwrite(tmp_str, strlen(tmp_str), 1, file);
					}
					sprintf(tmp_str, "%2d,", Mosa_fir.PerDirFirDirStrengths[i]);
					fwrite(tmp_str, strlen(tmp_str), 1, file);
				}
				sprintf(tmp_str, "},},\r\n},\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				sprintf(tmp_str, ".tbl2 = {//PerDirFirDirAmounts\r\n{{");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				for(i=0; i<9; i++) {
					if(!(i%32) && i!=0){
						sprintf(tmp_str, "\r\n");
						fwrite(tmp_str, strlen(tmp_str), 1, file);
					}
					sprintf(tmp_str, "%2d,", Mosa_fir.PerDirFirDirAmounts[i]);
					fwrite(tmp_str, strlen(tmp_str), 1, file);
				}
				sprintf(tmp_str, "},},\r\n},\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				sprintf(tmp_str, ".tbl3 = {//Coefs[9][25]\r\n{{");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				for(j=0; j<9; j++) {
					for(i=0; i<25; i++) {
						sprintf(tmp_str, "%3d,", Mosa_fir.Coefs[j][i]);
						fwrite(tmp_str, strlen(tmp_str), 1, file);
					}
					sprintf(tmp_str, "\r\n");
					fwrite(tmp_str, strlen(tmp_str), 1, file);
				}
				sprintf(tmp_str, "},},\r\n},\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				//ADJ_1ST_SHPCORING
				sprintf(tmp_str, "\r\nADJ_1ST_SHPCORING\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				amba_img_dsp_coring_t coring;
				amba_img_dsp_get_1st_sharpen_noise_sharpen_coring(&gTestIS2.Mode, &coring);
			//	sprintf(tmp_str, ".param[N] =  {{%d,}},\r\n",coring.FractionalBits);
			//	fwrite(tmp_str, strlen(tmp_str), 1, file);
				sprintf(tmp_str, ".tbl0 = {\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				for(i=0; i<256; i++) {
					if(!(i%32) && i!=0){
						sprintf(tmp_str, "\r\n");
						fwrite(tmp_str, strlen(tmp_str), 1, file);
					}
					sprintf(tmp_str, "%2d,", coring.Coring[i]);
					fwrite(tmp_str, strlen(tmp_str), 1, file);
				}
				sprintf(tmp_str, "\r\n},\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				sprintf(tmp_str, "\r\nADJ_MO_SHPCORING\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				amba_img_dsp_coring_t Mocoring;
				amba_img_dsp_get_mo_sharpen_noise_sharpen_coring(&gTestIS2.Mode, &Mocoring);
			//	sprintf(tmp_str, ".param[N] =  {{%d,}},\r\n",coring.FractionalBits);
			//	fwrite(tmp_str, strlen(tmp_str), 1, file);
				sprintf(tmp_str, ".tbl0 = {\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				for(i=0; i<256; i++) {
					if(!(i%32) && i!=0){
						sprintf(tmp_str, "\r\n");
						fwrite(tmp_str, strlen(tmp_str), 1, file);
					}
					sprintf(tmp_str, "%2d,", Mocoring.Coring[i]);
					fwrite(tmp_str, strlen(tmp_str), 1, file);
				}
				sprintf(tmp_str, "\r\n},\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				//ADJ_1ST_SHPCORING_INDEX_SCALE
				sprintf(tmp_str, "\r\nADJ_1ST_SHPCORING_INDEX_SCALE\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				amba_img_dsp_level_t idx_scale;
				amba_img_dsp_get_1st_sharpen_noise_sharpen_coring_index_scale(&gTestIS2.Mode, &idx_scale);
				sprintf(tmp_str, ".param[N] =  {{%d,   %d,   %d,     %d,  %d,  %d,     %d, }},\r\n",
					idx_scale.Low, idx_scale.LowDelta, idx_scale.LowStrength, idx_scale.MidStrength,
					idx_scale.High, idx_scale.HighDelta, idx_scale.HighStrength);
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				sprintf(tmp_str, "\r\nADJ_MO_SHPCORING_INDEX_SCALE\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				amba_img_dsp_level_t Moidx_scale;
				amba_img_dsp_get_mo_sharpen_noise_sharpen_coring_index_scale(&gTestIS2.Mode, &Moidx_scale);
				sprintf(tmp_str, ".param[N] =  {{%d,   %d,   %d,     %d,  %d,  %d,     %d, }},\r\n",
					Moidx_scale.Low, Moidx_scale.LowDelta, Moidx_scale.LowStrength, Moidx_scale.MidStrength,
					Moidx_scale.High, Moidx_scale.HighDelta, Moidx_scale.HighStrength);
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				//ADJ_1ST_SHPCORING_MIN_RESULT
				sprintf(tmp_str, "\r\nADJ_1ST_SHPCORING_MIN_RESULT\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				amba_img_dsp_level_t coring_min;
				amba_img_dsp_get_1st_sharpen_noise_sharpen_min_coring_result(&gTestIS2.Mode, &coring_min);
				sprintf(tmp_str, ".param[N] =  {{%d,   %d,   %d,     %d,  %d,  %d,     %d, }},\r\n",
					coring_min.Low, coring_min.LowDelta, coring_min.LowStrength, coring_min.MidStrength,
					coring_min.High, coring_min.HighDelta, coring_min.HighStrength);
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				sprintf(tmp_str, "\r\nADJ_MO_SHPCORING_MIN_RESULT\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				amba_img_dsp_level_t Mocoring_min;
				amba_img_dsp_get_mo_sharpen_noise_sharpen_min_coring_result(&gTestIS2.Mode, &Mocoring_min);
				sprintf(tmp_str, ".param[N] =  {{%d,   %d,   %d,     %d,  %d,  %d,     %d, }},\r\n",
					Mocoring_min.Low, Mocoring_min.LowDelta, Mocoring_min.LowStrength, Mocoring_min.MidStrength,
					Mocoring_min.High, Mocoring_min.HighDelta, Mocoring_min.HighStrength);
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				//ADJ_1ST_SHPCORING_SCALE_CORING
				sprintf(tmp_str, "\r\nADJ_1ST_SHPCORING_SCALE_CORING\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				amba_img_dsp_level_t scale_coring;
				amba_img_dsp_get_1st_sharpen_noise_sharpen_scale_coring(&gTestIS2.Mode, &scale_coring);
				sprintf(tmp_str, ".param[N] =  {{%d,   %d,   %d,     %d,  %d,  %d,     %d, }},\r\n",
					scale_coring.Low, scale_coring.LowDelta, scale_coring.LowStrength, scale_coring.MidStrength,
					scale_coring.High, scale_coring.HighDelta, scale_coring.HighStrength);
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				sprintf(tmp_str, "\r\nADJ_MO_SHPCORING_SCALE_CORING\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				amba_img_dsp_level_t Moscale_coring;
				amba_img_dsp_get_mo_sharpen_noise_sharpen_scale_coring(&gTestIS2.Mode, &Moscale_coring);
				sprintf(tmp_str, ".param[N] =  {{%d,   %d,   %d,     %d,  %d,  %d,     %d, }},\r\n",
					Moscale_coring.Low, Moscale_coring.LowDelta, Moscale_coring.LowStrength, Moscale_coring.MidStrength,
					Moscale_coring.High, Moscale_coring.HighDelta, Moscale_coring.HighStrength);
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				sprintf(tmp_str, "\r\nADJ_Final_SHPBOTH\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				amba_img_dsp_sharpen_both_t sb_both;
				amba_img_dsp_get_final_sharpen_noise_both(&gTestIS2.Mode, &sb_both);
				sprintf(tmp_str, ".param[N] =  {{%d,   %d,   %d,         %d,      %d,   %d,}},\r\n",
					sb_both.Enable, sb_both.Mode, sb_both.EdgeThresh, sb_both.WideEdgeDetect,
					sb_both.MaxChangeUp5x5, sb_both.MaxChangeDown5x5);
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				//ADJ_FINAL_SHPNOISE
				sprintf(tmp_str, "\r\nADJ_FINAL_SHPNOISE\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				amba_img_dsp_sharpen_noise_t sb_noise;
				amba_img_dsp_get_final_sharpen_noise_noise(&gTestIS2.Mode, &sb_noise);
				sprintf(tmp_str, ".param[N] =  {{%d,    %d,     %d,     %d,   %d,   %d,     %d,   %d,  %d,   %d,    %d,  %d, %d,     %d,    %d,	%d,	%d,	%d,	%d }},\r\n",
					sb_noise.MaxChangeUp, sb_noise.MaxChangeDown, sb_noise.SpatialFir.Specify, sb_noise.SpatialFir.StrengthIso, sb_noise.SpatialFir.StrengthDir,
					sb_noise.SpatialFir.EdgeThresh, sb_noise.SpatialFir.WideEdgeDetect,
					sb_noise.LevelStrAdjust.Low, sb_noise.LevelStrAdjust.LowDelta, sb_noise.LevelStrAdjust.LowStrength, sb_noise.LevelStrAdjust.MidStrength,
					sb_noise.LevelStrAdjust.High, sb_noise.LevelStrAdjust.HighDelta, sb_noise.LevelStrAdjust.HighStrength,
					sb_noise.LevelStrAdjustNotT0T1LevelBased,sb_noise.T0,sb_noise.T1,sb_noise.AlphaMin,sb_noise.AlphaMax);
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				sprintf(tmp_str, ".tbl0 = {//PerDirFirIsoStrengths\r\n{{");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				for(i=0; i<9; i++) {
					if(!(i%32) && i!=0){
						sprintf(tmp_str, "\r\n");
						fwrite(tmp_str, strlen(tmp_str), 1, file);
					}
					sprintf(tmp_str, "%2d,", sb_noise.SpatialFir.PerDirFirIsoStrengths[i]);
					fwrite(tmp_str, strlen(tmp_str), 1, file);
				}
				sprintf(tmp_str, "},},\r\n},\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				sprintf(tmp_str, ".tbl1 = {//PerDirFirDirStrengths\r\n{{");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				for(i=0; i<9; i++) {
					if(!(i%32) && i!=0){
						sprintf(tmp_str, "\r\n");
						fwrite(tmp_str, strlen(tmp_str), 1, file);
					}
					sprintf(tmp_str, "%2d,", sb_noise.SpatialFir.PerDirFirDirStrengths[i]);
					fwrite(tmp_str, strlen(tmp_str), 1, file);
				}
				sprintf(tmp_str, "},},\r\n},\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				sprintf(tmp_str, ".tbl2 = {//PerDirFirDirAmounts\r\n{{");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				for(i=0; i<9; i++) {
					if(!(i%32) && i!=0){
						sprintf(tmp_str, "\r\n");
						fwrite(tmp_str, strlen(tmp_str), 1, file);
					}
					sprintf(tmp_str, "%2d,", sb_noise.SpatialFir.PerDirFirDirAmounts[i]);
					fwrite(tmp_str, strlen(tmp_str), 1, file);
				}
				sprintf(tmp_str, "},},\r\n},\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				sprintf(tmp_str, ".tbl3 = {//Coefs[9][25]\r\n{{");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				for(j=0; j<9; j++) {
					for(i=0; i<25; i++) {
						sprintf(tmp_str, "%3d,", sb_noise.SpatialFir.Coefs[j][i]);
						fwrite(tmp_str, strlen(tmp_str), 1, file);
					}
					sprintf(tmp_str, "\r\n");
					fwrite(tmp_str, strlen(tmp_str), 1, file);
				}
				sprintf(tmp_str, "},},\r\n},\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				//ADJ_FINAL_SHPFIR
				sprintf(tmp_str, "\r\nADJ_FINAL_SHPFIR\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				amba_img_dsp_fir_t sb_fir;
				amba_img_dsp_get_final_sharpen_noise_sharpen_fir(&gTestIS2.Mode, &sb_fir);
				sprintf(tmp_str, ".param[N] =  {{%d,   %d,   %d,    %d,     %d,}},\r\n",
					sb_fir.Specify, sb_fir.StrengthIso, sb_fir.StrengthDir, sb_fir.EdgeThresh, sb_fir.WideEdgeDetect);
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				sprintf(tmp_str, ".tbl0 = {//PerDirFirIsoStrengths\r\n{{");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				for(i=0; i<9; i++) {
					if(!(i%32) && i!=0){
						sprintf(tmp_str, "\r\n");
						fwrite(tmp_str, strlen(tmp_str), 1, file);
					}
					sprintf(tmp_str, "%2d,", sb_fir.PerDirFirIsoStrengths[i]);
					fwrite(tmp_str, strlen(tmp_str), 1, file);
				}
				sprintf(tmp_str, "},},\r\n},\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				sprintf(tmp_str, ".tbl1 = {//PerDirFirDirStrengths\r\n{{");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				for(i=0; i<9; i++) {
					if(!(i%32) && i!=0){
						sprintf(tmp_str, "\r\n");
						fwrite(tmp_str, strlen(tmp_str), 1, file);
					}
					sprintf(tmp_str, "%2d,", sb_fir.PerDirFirDirStrengths[i]);
					fwrite(tmp_str, strlen(tmp_str), 1, file);
				}
				sprintf(tmp_str, "},},\r\n},\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				sprintf(tmp_str, ".tbl2 = {//PerDirFirDirAmounts\r\n{{");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				for(i=0; i<9; i++) {
					if(!(i%32) && i!=0){
						sprintf(tmp_str, "\r\n");
						fwrite(tmp_str, strlen(tmp_str), 1, file);
					}
					sprintf(tmp_str, "%2d,", sb_fir.PerDirFirDirAmounts[i]);
					fwrite(tmp_str, strlen(tmp_str), 1, file);
				}
				sprintf(tmp_str, "},},\r\n},\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				sprintf(tmp_str, ".tbl3 = {//Coefs[9][25]\r\n{{");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				for(j=0; j<9; j++) {
					for(i=0; i<25; i++) {
						sprintf(tmp_str, "%3d,", sb_fir.Coefs[j][i]);
						fwrite(tmp_str, strlen(tmp_str), 1, file);
					}
					sprintf(tmp_str, "\r\n");
					fwrite(tmp_str, strlen(tmp_str), 1, file);
				}
				sprintf(tmp_str, "},},\r\n},\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				//ADJ_FINAL_SHPCORING
				sprintf(tmp_str, "\r\nADJ_FINAL_SHPCORING\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				amba_img_dsp_coring_t sb_coring;
				amba_img_dsp_get_final_sharpen_noise_sharpen_coring(&gTestIS2.Mode, &sb_coring);
			//	sprintf(tmp_str, ".param[N] =  {{%d,}},\r\n",coring.FractionalBits);
			//	fwrite(tmp_str, strlen(tmp_str), 1, file);
				sprintf(tmp_str, ".tbl0 = {\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				for(i=0; i<256; i++) {
					if(!(i%32) && i!=0){
						sprintf(tmp_str, "\r\n");
						fwrite(tmp_str, strlen(tmp_str), 1, file);
					}
					sprintf(tmp_str, "%2d,", sb_coring.Coring[i]);
					fwrite(tmp_str, strlen(tmp_str), 1, file);
				}
				sprintf(tmp_str, "\r\n},\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				//ADJ_FINAL_SHPCORING_INDEX_SCALE
				sprintf(tmp_str, "\r\nADJ_FINAL_SHPCORING_INDEX_SCALE\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				amba_img_dsp_level_t sb_idx_scale;
				amba_img_dsp_get_final_sharpen_noise_sharpen_coring_index_scale(&gTestIS2.Mode, &sb_idx_scale);
				sprintf(tmp_str, ".param[N] =  {{%d,   %d,   %d,     %d,  %d,  %d,     %d, }},\r\n",
					sb_idx_scale.Low, sb_idx_scale.LowDelta, sb_idx_scale.LowStrength, sb_idx_scale.MidStrength,
					sb_idx_scale.High, sb_idx_scale.HighDelta, sb_idx_scale.HighStrength);
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				//ADJ_FINAL_SHPCORING_MIN_RESULT
				sprintf(tmp_str, "\r\nADJ_FINAL_SHPCORING_MIN_RESULT\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				amba_img_dsp_level_t sb_coring_min;
				amba_img_dsp_get_final_sharpen_noise_sharpen_min_coring_result(&gTestIS2.Mode, &sb_coring_min);
				sprintf(tmp_str, ".param[N] =  {{%d,   %d,   %d,     %d,  %d,  %d,     %d, }},\r\n",
					sb_coring_min.Low, sb_coring_min.LowDelta, sb_coring_min.LowStrength, sb_coring_min.MidStrength,
					sb_coring_min.High, sb_coring_min.HighDelta, sb_coring_min.HighStrength);
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				//ADJ_FINAL_SHPCORING_SCALE_CORING
				sprintf(tmp_str, "\r\nADJ_FINAL_SHPCORING_SCALE_CORING\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				amba_img_dsp_level_t sb_scale_coring;
				amba_img_dsp_get_final_sharpen_noise_sharpen_scale_coring(&gTestIS2.Mode, &sb_scale_coring);
				sprintf(tmp_str, ".param[N] =  {{%d,   %d,   %d,     %d,  %d,  %d,     %d, }},\r\n",
					sb_scale_coring.Low, sb_scale_coring.LowDelta, sb_scale_coring.LowStrength, sb_scale_coring.MidStrength,
					sb_scale_coring.High, sb_scale_coring.HighDelta, sb_scale_coring.HighStrength);
				fwrite(tmp_str, strlen(tmp_str), 1, file);

				//ADJ_VIDEO_MCTF
				sprintf(tmp_str, "\r\nADJ_VIDEO_MCTF\r\n");
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				amba_img_dsp_video_mctf_info_t mctf;
				amba_img_dsp_get_video_mctf(&gTestIS2.Mode, &mctf);
				sprintf(tmp_str, ".param[N] =  {{%d, %d,%d,%d,%d,%d,%d,%d,%d, %d,      %d,   %d,    %d,  %d,  %d,	%d,	%d,	%d,	%d,	%d,	%d,	%d, %d,	%d,	%d,	%d,	%d,	%d,	%d,	%d,	%d,	%d,	%d,}},\r\n",
					mctf.Enable,
					mctf.YMaxChange,mctf.UMaxChange,mctf.VMaxChange,mctf.WeightingBasedOnLocalMotion,
					mctf.Threshold0[0],mctf.Threshold0[1],mctf.Threshold0[2],mctf.Threshold0[3],
					mctf.Threshold1[0],mctf.Threshold1[1],mctf.Threshold1[2],mctf.Threshold1[3],
					mctf.Threshold2[0],mctf.Threshold2[1],mctf.Threshold2[2],mctf.Threshold2[3],
					mctf.Threshold3[0],mctf.Threshold3[1],mctf.Threshold3[2],mctf.Threshold3[3],
					mctf.Alpha1[0],mctf.Alpha1[1],mctf.Alpha1[2],mctf.Alpha1[3],
					mctf.Alpha2[0],mctf.Alpha2[1],mctf.Alpha2[2],mctf.Alpha2[3],
					mctf.Alpha3[0],mctf.Alpha3[1],mctf.Alpha3[2],mctf.Alpha3[3]);
				fwrite(tmp_str, strlen(tmp_str), 1, file);
				}

                            //ADJ_WIDE_CHROMANF
                        sprintf(tmp_str, "\r\nADJ_WIDE_CHROMANF\r\n");
                        fwrite(tmp_str, strlen(tmp_str), 1, file);
                        amba_img_dsp_chroma_filter_t wide_cf;
                        amba_img_dsp_get_wide_chroma_filter(&gTestIS2.Mode, &wide_cf);
                        sprintf(tmp_str, ".param[N] =  {{%d, %d, %d, %d, %d, %d,}},\r\n",
                         wide_cf.Enable, wide_cf.NoiseLevelCb, wide_cf.NoiseLevelCr, wide_cf.OriginalBlendStrengthCb, wide_cf.OriginalBlendStrengthCr, wide_cf.Radius);
                        fwrite(tmp_str, strlen(tmp_str), 1, file);



                                       //ADJ_WIDE_CHROMANF_COMBINE
                        sprintf(tmp_str, "\r\nADJ_WIDE_CHROMANF_COMBINE\r\n");
                        fwrite(tmp_str, strlen(tmp_str), 1, file);
                        AMBA_DSP_IMG_HISO_CHROMA_FILTER_COMBINE_s wide_cf_combine;
                        amba_img_dsp_get_wide_chroma_filter_combine(&gTestIS2.Mode, &wide_cf_combine);
                        sprintf(tmp_str, ".param[N] =  {{%d, %d, %d, %d, %d, %d,%d,%d,%d,%d,}},\r\n",
                        wide_cf_combine.T0Cb,wide_cf_combine.T0Cr,wide_cf_combine.T1Cb,wide_cf_combine.T1Cr,
                        wide_cf_combine.AlphaMaxCb,wide_cf_combine.AlphaMaxCr,wide_cf_combine.AlphaMinCb,wide_cf_combine.AlphaMinCr,
                        wide_cf_combine.MaxChangeCb,wide_cf_combine.MaxChangeCr);
                        fwrite(tmp_str, strlen(tmp_str), 1, file);
				fclose(file);

			break;
		default:
			printf("unknow work mode %d\n", work_mode);
			return -1;
			break;
	}
	return 0;
}


int dump_debug_cfg(void *cfg_addr)
{
	printf("dump debug section to %s\n", folder_name);

	a12_high_iso_param_t* h_cfg = (a12_high_iso_param_t*)cfg_addr;
	printf("get debug step %d mode %d\n", h_cfg->share.debug_step_id, h_cfg->share.debug_mode);
	printf("debug cfg_addr 0x%x debug_addr 0x%x 0x%x\n", h_cfg->share.debug_config_addr,
							h_cfg->share.debug_addr[0], h_cfg->share.debug_addr[1]);
	printf("pitch %d %d width %d %d height %d %d\n", h_cfg->share.debug_pitch[0], h_cfg->share.debug_pitch[1],
							h_cfg->share.debug_width[0], h_cfg->share.debug_width[1],
							h_cfg->share.debug_height[0], h_cfg->share.debug_height[1]);

	int y_size = h_cfg->share.debug_pitch[0]*h_cfg->share.debug_height[0];
	u32 y_src = h_cfg->share.debug_addr[0];
	int uv_size = h_cfg->share.debug_pitch[1]*h_cfg->share.debug_height[1];
	u32 uv_src = h_cfg->share.debug_addr[1];
	u32 debug_cfg_src = h_cfg->share.debug_config_addr;
	int debug_cfg_size = 150*1024;

	char fn[64], shell_cmd[128];
	if(strlen(folder_name)==0)
		sprintf(folder_name, "/mnt/debug");
	sprintf(shell_cmd, "mkdir -p %s", folder_name);
	system(shell_cmd);

	if(debug_cfg_src != 0) {
		sprintf(fn, "step%d_mode%d_cfg.bin", h_cfg->share.debug_step_id, h_cfg->share.debug_mode);
		sprintf(shell_cmd, "amba_debug -r 0x%x -s 0x%x -f %s/%s", debug_cfg_src, debug_cfg_size, folder_name, fn);
		system(shell_cmd);
	}
	if(y_src != 0) {
		sprintf(fn, "step%d_mode%d_w%d_h%d.y", h_cfg->share.debug_step_id, h_cfg->share.debug_mode,
						h_cfg->share.debug_pitch[0], h_cfg->share.debug_height[0]);
		sprintf(shell_cmd, "amba_debug -r 0x%x -s 0x%x -f %s/%s", y_src, y_size, folder_name, fn);
		system(shell_cmd);
	}
	if(uv_src != 0) {
		sprintf(fn, "step%d_mode%d_w%d_h%d.uv", h_cfg->share.debug_step_id, h_cfg->share.debug_mode,
						h_cfg->share.debug_pitch[1], h_cfg->share.debug_height[1]);
		sprintf(shell_cmd, "amba_debug -r 0x%x -s 0x%x -f %s/%s", uv_src, uv_size, folder_name, fn);
		system(shell_cmd);
	}

	return 0;
}
