#!/bin/sh
#
# Init system config
#

start()
{
	find /etc/sysctl.d -type f -name "*.conf" -exec /sbin/sysctl -p "{}" \;
}

stop()
{
	/bin/true
}

restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

