#
# ldc_convert.sh
#
# History:
#       2015/07/17 - [niu zhifeng] created file
#
# Copyright (c) 2015 Ambarella, Inc.
#
# This file and its contents ("Software") are protected by intellectual
# property rights including, without limitation, U.S. and/or foreign
# copyrights. This Software is also the confidential and proprietary
# information of Ambarella, Inc. and its licensors. You may not use, reproduce,
# disclose, distribute, modify, or otherwise prepare derivative works of this
# Software or any portion thereof except pursuant to a signed license agreement
# or nondisclosure agreement with Ambarella, Inc. or its authorized affiliates.
# In the absence of such an agreement, you agree to promptly notify and return
# this Software to Ambarella, Inc.
#
# THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF NON-INFRINGEMENT,
# MERCHANTABILITY, AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
# IN NO EVENT SHALL AMBARELLA, INC. OR ITS AFFILIATES BE LIABLE FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; COMPUTER FAILURE OR MALFUNCTION; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#
#

#!/bin/sh

#Filename:convert tables

#function: this shell is to generate the arrays of ldc from the ldc table


usage()
{
        echo "Usage: ldc_convert.sh htable vtable me1table result_file"
        echo "Parameters description:"
        echo "htable:hon_table file generated by test_ldc"
        echo "vtable:ver_table file generated by test_ldc"
        echo "me1table:me1_ver_table file generated by test_ldc"
        echo "result_file:the file to save arrays"
}



run()
{
        htable="$1_tmp"
        vtable="$2_tmp"
        me1table="$3_tmp"
        result="$4_tmp"

        cp -f $1 $htable
        cp -f $2 $vtable
        cp -f $3 $me1table

        rm -f $4

        sed -i 's/\t/,/g' $htable
        sed -i 's/\t/,/g' $vtable
        sed -i 's/\t/,/g' $me1table

        echo "static s16 warp_ctrl_h_table[] = {" >> $4

        while read LINE
        do
        echo $LINE >> $4
        done < $htable

        echo "};" >> $4

        echo "static s16 warp_ctrl_v_table[] = {" >> $4

        while read LINE
        do
        echo $LINE >> $4
        done < $vtable

        echo "};" >> $4

        echo "static s16 warp_ctrl_me1_table[] = {" >> $4

        while read LINE
        do echo $LINE >> $4
        done < $me1table

        echo "};" >> $4

        rm -f $htable
        rm -f $vtable
        rm -f $me1table
}

if [ ! -n "$1" ] ; then
        usage
elif [ ! -n "$2" ] ; then
        usage
elif [ ! -n "$3" ] ; then
        usage
elif [ ! -n "$4" ] ; then
        usage
else
        run $1 $2 $3 $4
fi
