
/**
 * gic.h
 *
 * History:
 *    2015/12/1 - Jorney(qtu@ambarella.com) created file
 *
 * Copyright (c) 2015 Ambarella, Inc.
 *
 * This file and its contents ("Software") are protected by intellectual
 * property rights including, without limitation, U.S. and/or foreign
 * copyrights. This Software is also the confidential and proprietary
 * information of Ambarella, Inc. and its licensors. You may not use, reproduce,
 * disclose, distribute, modify, or otherwise prepare derivative works of this
 * Software or any portion thereof except pursuant to a signed license agreement
 * or nondisclosure agreement with Ambarella, Inc. or its authorized affiliates.
 * In the absence of such an agreement, you agree to promptly notify and return
 * this Software to Ambarella, Inc.
 *
 * THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF NON-INFRINGEMENT,
 * MERCHANTABILITY, AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL AMBARELLA, INC. OR ITS AFFILIATES BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; COMPUTER FAILURE OR MALFUNCTION; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 */
#ifndef __AMBOOT_GIC_H
#define __AMBOOT_GIC_H

#include <ambhw/chip.h>

/* ==========================================================================*/
#if (CHIP_REV == S5) || (CHIP_REV == S5L)
#define GIC_BASE		0xF0040000
#else
#define GIC_BASE		0xF3000000
#endif

#define GICD_OFFSET			0x1000
#define GICC_OFFSET			0x2000

#define GICD_BASE			(GIC_BASE + GICD_OFFSET)
#define GICC_BASE			(GIC_BASE + GICC_OFFSET)
#define GICD_REG(x)			(GICD_BASE + (x))
#define GICC_REG(x)			(GICC_BASE + (x))


/* GIC distribute */
#define GICD_CTLR			0x0000
#define GICD_TYPER			0x0004
#define GICD_IIDR			0x0008
#define GICD_STATUSR			0x0010
#define GICD_SETSPI_NSR			0x0040
#define GICD_CLRSPI_NSR			0x0048
#define GICD_SETSPI_SR			0x0050
#define GICD_CLRSPI_SR			0x0058
#define GICD_SEIR			0x0068
#define GICD_IGROUPR			0x0080
#define GICD_ISENABLER			0x0100
#define GICD_ICENABLER			0x0180
#define GICD_ISPENDR			0x0200
#define GICD_ICPENDR			0x0280
#define GICD_ISACTIVER			0x0300
#define GICD_ICACTIVER			0x0380
#define GICD_IPRIORITYR			0x0400
#define GICD_ICFGR			0x0C00
#define GICD_IGRPMODR			0x0D00
#define GICD_NSACR			0x0E00
#define GICD_IROUTER			0x6000
#define GICD_IDREGS			0xFFD0
#define GICD_PIDR2			0xFFE8
#define GICD_ITARGETSR			0x0800
#define GICD_SGIR			0x0F00
#define GICD_CPENDSGIR			0x0F10
#define GICD_SPENDSGIR			0x0F20

/* GIC cpu interface */
#define GICC_CTRL			0x00
#define GICC_PMR			0x04
#define GICC_BPR			0x08
#define GICC_IAR			0x0c
#define GICC_EOIR			0x10
#define GICC_RPR			0x14
#define GICC_HPPIR			0x18
#define GICC_ABPR			0x1c
#define GICC_AIAR			0x20
#define GICC_AEOIR			0x24
#define GICC_AHPPIR			0x28
#define GICC_APRN			0xd0
#define GICC_IIDR			0xfc

/* ==========================================================================*/
#define ICC_CTLR_EL3			S3_6_C12_C12_4
#define ICC_SRE_EL3			S3_6_C12_C12_5
#define ICC_IGRPEN1_EL3			S3_6_C12_C12_7

/* ==========================================================================*/
#define SGI_INT_VEC(x)			(x)
#define PPI_INT_VEC(x)			(x)
#define SPI_INT_VEC(x)			((x) + 32)

/* ==========================================================================*/
#if (CHIP_REV == S5)
#define AXI_SOFT_IRQ0			SPI_INT_VEC(0)
#define AXI_SOFT_IRQ1			SPI_INT_VEC(1)
#define AXI_SOFT_IRQ2			SPI_INT_VEC(2)
#define AXI_SOFT_IRQ3			SPI_INT_VEC(3)
#define AXI_SOFT_IRQ4			SPI_INT_VEC(4)
#define AXI_SOFT_IRQ5			SPI_INT_VEC(5)
#define AXI_SOFT_IRQ6			SPI_INT_VEC(6)
#define TIMER1_IRQ			SPI_INT_VEC(7)
#define TIMER2_IRQ			SPI_INT_VEC(8)
#define TIMER3_IRQ			SPI_INT_VEC(9)
#define TIMER4_IRQ			SPI_INT_VEC(10)
#define TIMER5_IRQ			SPI_INT_VEC(11)
#define TIMER6_IRQ			SPI_INT_VEC(12)
#define TIMER7_IRQ			SPI_INT_VEC(13)
#define TIMER8_IRQ			SPI_INT_VEC(14)
#define PMU_IRQ				SPI_INT_VEC(15)
#define AXI_SOFT_IRQ7			SPI_INT_VEC(16)
#define AXI_SOFT_IRQ8			SPI_INT_VEC(17)
#define AXI_SOFT_IRQ9			SPI_INT_VEC(18)
#define AXI_SOFT_IRQ10			SPI_INT_VEC(19)
#define AXI_SOFT_IRQ11			SPI_INT_VEC(20)
#define AXI_SOFT_IRQ12			SPI_INT_VEC(21)
#define AXI_SOFT_IRQ13			SPI_INT_VEC(22)
#define TIMER11_IRQ			SPI_INT_VEC(23)
#define TIMER12_IRQ			SPI_INT_VEC(24)
#define TIMER13_IRQ			SPI_INT_VEC(25)
#define TIMER14_IRQ			SPI_INT_VEC(26)
#define TIMER15_IRQ			SPI_INT_VEC(27)
#define TIMER16_IRQ			SPI_INT_VEC(28)
#define TIMER17_IRQ			SPI_INT_VEC(29)
#define TIMER18_IRQ			SPI_INT_VEC(30)
#define PMU1_IRQ			SPI_INT_VEC(31)

#define IDSP_VIN_STAT_IRQ		SPI_INT_VEC(32)
#define IDSP_VIN_MVSYNC_IRQ		SPI_INT_VEC(33)
#define IDSP_VIN_VSYNC_IRQ		SPI_INT_VEC(34)
#define IDSP_VIN_SOF_IRQ		SPI_INT_VEC(35)
#define IDSP_VIN_DVSYNC_IRQ		SPI_INT_VEC(36)
#define IDSP_VIN_LAST_PIXEL_IRQ		SPI_INT_VEC(37)
#define IDSP_PIP_STAT_IRQ		SPI_INT_VEC(38)
#define IDSP_PIP_MVSYNC_IRQ		SPI_INT_VEC(39)
#define IDSP_PIP_VSYNC_IRQ		SPI_INT_VEC(40)
#define IDSP_PIP_SOF_IRQ		SPI_INT_VEC(41)
#define IDSP_PIP_DVSYNC_IRQ		SPI_INT_VEC(42)
#define IDSP_PIP_LAST_PIXEL_IRQ		SPI_INT_VEC(43)
#define VOUT_TV_SYNC_IRQ		SPI_INT_VEC(44)
#define VOUT_LCD_SYNC_IRQ		SPI_INT_VEC(45)
#define CODE_VDSP_0_IRQ			SPI_INT_VEC(46)
#define CODE_VDSP_1_IRQ			SPI_INT_VEC(47)
#define CODE_VDSP_2_IRQ			SPI_INT_VEC(48)
#define CODE_VDSP_3_IRQ			SPI_INT_VEC(49)
#define CODE_VDSP_4_IRQ			SPI_INT_VEC(50)
#define CODE_VDSP_5_IRQ			SPI_INT_VEC(51)
#define CODE_VDSP_6_IRQ			SPI_INT_VEC(52)
#define CODE_VDSP_7_IRQ			SPI_INT_VEC(53)
#define VIN_IRQ				SPI_INT_VEC(54)
#define ORC_VOUT0_IRQ			SPI_INT_VEC(55)
#define VOUT_IRQ			SPI_INT_VEC(56)
#define VDSP_ORC_BKPT_IRQ		SPI_INT_VEC(57)
#define VDSP_EORC0_BKPT_IRQ		SPI_INT_VEC(58)
#define VDSP_DORC_BRPT_IRQ		SPI_INT_VEC(59)
#define VDSP_PIP_CODING_IRQ		SPI_INT_VEC(60)
#define USB3_IRQ			SPI_INT_VEC(61)
#define TIMER10_IRQ			SPI_INT_VEC(62)
#define TIMER9_IRQ			SPI_INT_VEC(63)

#define CANC_IRQ			SPI_INT_VEC(64)
#define ETH_IRQ				SPI_INT_VEC(65)
#define USB_EHCI_IRQ			SPI_INT_VEC(66)
#define USB_OHCI_IRQ			SPI_INT_VEC(67)
#define USBC_IRQ			SPI_INT_VEC(68)
#define DMA_IRQ				SPI_INT_VEC(69)
#define DMA_FIOS_IRQ			SPI_INT_VEC(70)
#define FIOS_ECC_IRQ			SPI_INT_VEC(71)
#define FIOCMD_IRQ			SPI_INT_VEC(72)
#define FIODMA_IRQ			SPI_INT_VEC(73)
#define GDMA_IRQ			SPI_INT_VEC(74)
#define SDXC_IRQ			SPI_INT_VEC(75)
#define SDIO_IRQ			SPI_INT_VEC(76)
#define SD_IRQ				SPI_INT_VEC(77)
#define NOR_SPI				SPI_INT_VEC(78)
#define SSI_MASTER1_IRQ			SPI_INT_VEC(79)
#define SSI_MASTER0_IRQ			SPI_INT_VEC(80)
#define SSI_SLAVE_IRQ			SPI_INT_VEC(81)
#define UART1_IRQ			SPI_INT_VEC(82)
#define IDC2_IRQ			SPI_INT_VEC(83)
#define IDC1_IRQ			SPI_INT_VEC(84)
#define IDC0_IRQ			SPI_INT_VEC(85)
#define IRIF_IRQ			SPI_INT_VEC(86)
#define I2STX_IRQ			SPI_INT_VEC(87)
#define I2SRX_IRQ			SPI_INT_VEC(88)
#define IDC_SLAVE_IRQ			SPI_INT_VEC(89)
#define HIF_ARM2_IRQ			SPI_INT_VEC(90)
#define HIF_ARM1_IRQ			SPI_INT_VEC(91)
#define TS_CH1_RX_IRQ			SPI_INT_VEC(92)
#define TS_CH0_RX_IRQ			SPI_INT_VEC(93)
#define TS_CH1_TX_IRQ			SPI_INT_VEC(94)
#define TS_CH0_TX_IRQ			SPI_INT_VEC(95)

#define USBVBUS_IRQ			SPI_INT_VEC(96)
#define USB_DIGITAL_ID_CHANGE_IRQ	SPI_INT_VEC(97)
#define USB_CONNECT_CHANGE_IRQ		SPI_INT_VEC(98)
#define USB_CHARGE_IRQ			SPI_INT_VEC(99)
#define SD2CD_IRQ			SPI_INT_VEC(100)
#define SD1CD_IRQ			SPI_INT_VEC(101)
#define SD0CD_IRQ			SPI_INT_VEC(102)
#define ADC_LEVEL_IRQ			SPI_INT_VEC(103)
#define HDMI_IRQ			SPI_INT_VEC(104)
#define WDT_IRQ				SPI_INT_VEC(105)
#define SLIM_IRQ			SPI_INT_VEC(106)
#define ETH_PMT_IRQ			SPI_INT_VEC(107)
#define UART0_IRQ			SPI_INT_VEC(108)
#define MOTOR_IRQ			SPI_INT_VEC(109)
/* SPI_INT_VEC(110) ~ SPI_INT_VEC(112) are NULL */
#define L2CC_ERR_IRQ			SPI_INT_VEC(113)
#define L2CC_INTR_IRQ			SPI_INT_VEC(114)
#define L2CC_INTR1_IRQ			SPI_INT_VEC(115)
#define AXI_SWI_IRQ			SPI_INT_VEC(116)
#define AXI_SWI1_IRQ			SPI_INT_VEC(117)
/* SPI_INT_VEC(118) ~ SPI_INT_VEC(119) are NULL */
#define GPIO4_IRQ			SPI_INT_VEC(120)
#define GPIO3_IRQ			SPI_INT_VEC(121)
#define GPIO2_IRQ			SPI_INT_VEC(122)
#define GPIO1_IRQ			SPI_INT_VEC(123)
#define GPIO0_IRQ			SPI_INT_VEC(124)
#define USB3_BC_IRQ			SPI_INT_VEC(125)
#define TIMER20_IRQ			SPI_INT_VEC(126)
#define TIMER19_IRQ			SPI_INT_VEC(127)

#define CRYPTO0_MD5_IRQ			SPI_INT_VEC(128)
#define CRYPTO1_MD5_IRQ			SPI_INT_VEC(129)
#define CRYPTO2_MD5_IRQ			SPI_INT_VEC(130)
#define CRYPTO3_MD5_IRQ			SPI_INT_VEC(131)
#define CRYPTO0_DES_IRQ			SPI_INT_VEC(132)
#define CRYPTO1_DES_IRQ			SPI_INT_VEC(133)
#define CRYPTO2_DES_IRQ			SPI_INT_VEC(134)
#define CRYPTO3_DES_IRQ			SPI_INT_VEC(135)
#define CRYPTO0_AES_IRQ			SPI_INT_VEC(136)
#define CRYPTO1_AES_IRQ			SPI_INT_VEC(137)
#define CRYPTO2_AES_IRQ			SPI_INT_VEC(138)
#define CRYPTO3_AES_IRQ			SPI_INT_VEC(139)
#define CRYPTO0_SHA1_IRQ		SPI_INT_VEC(140)
#define CRYPTO1_SHA1_IRQ		SPI_INT_VEC(141)
#define CRYPTO2_SHA1_IRQ		SPI_INT_VEC(142)
#define CRYPTO3_SHA1_IRQ		SPI_INT_VEC(143)
#define IDSP_PIP3_ASYNC_IRQ		SPI_INT_VEC(144)
#define IDSP_PIP3_STAT_IRQ		SPI_INT_VEC(145)
#define IDSP_PIP3_SOF_IRQ		SPI_INT_VEC(146)
#define IDSP_PIP3_LAST_PIXEL_IRQ	SPI_INT_VEC(147)
#define IDSP_PIP3_DVSYNC_IRQ		SPI_INT_VEC(148)
#define IDSP_PIP2_ASYNC_IRQ		SPI_INT_VEC(149)
#define IDSP_PIP2_STAT_IRQ		SPI_INT_VEC(150)
#define IDSP_PIP2_SOF_IRQ		SPI_INT_VEC(151)
#define IDSP_PIP2_LAST_PIXEL_IRQ	SPI_INT_VEC(152)
#define IDSP_PIP2_DVSYNC_IRQ		SPI_INT_VEC(153)
#define FDET_IRQ			SPI_INT_VEC(154)
#define CODE_PIP3_IRQ			SPI_INT_VEC(155)
#define CODE_PIP2_IRQ			SPI_INT_VEC(156)
#define PWC_ALRAM			SPI_INT_VEC(157)

#define NR_IRQS				SPI_INT_VEC(158)

#elif (CHIP_REV == S5L)
#define TIMER1_IRQ			SPI_INT_VEC(0)
#define TIMER2_IRQ			SPI_INT_VEC(1)
#define TIMER3_IRQ			SPI_INT_VEC(2)
#define TIMER4_IRQ			SPI_INT_VEC(3)
#define TIMER5_IRQ			SPI_INT_VEC(4)
#define TIMER6_IRQ			SPI_INT_VEC(5)
#define TIMER7_IRQ			SPI_INT_VEC(6)
#define AXI_SOFT_IRQ0			SPI_INT_VEC(7)
#define AXI_SOFT_IRQ1			SPI_INT_VEC(8)
#define AXI_SOFT_IRQ2			SPI_INT_VEC(9)
#define AXI_SOFT_IRQ3			SPI_INT_VEC(10)
#define AXI_SOFT_IRQ4			SPI_INT_VEC(11)
#define AXI_SOFT_IRQ5			SPI_INT_VEC(12)
#define AXI_SOFT_IRQ6			SPI_INT_VEC(13)
#define AXI_SOFT_IRQ7			SPI_INT_VEC(14)
#define AXI_SOFT_IRQ8			SPI_INT_VEC(15)
#define AXI_SOFT_IRQ9			SPI_INT_VEC(16)
#define AXI_SOFT_IRQ10			SPI_INT_VEC(17)
#define AXI_SOFT_IRQ11			SPI_INT_VEC(18)
#define AXI_SOFT_IRQ12			SPI_INT_VEC(19)
#define AXI_SOFT_IRQ13			SPI_INT_VEC(20)
#define AXI_SWI_IRQ			SPI_INT_VEC(21)
#define AXI_SWI1_IRQ			SPI_INT_VEC(22)
#define PMU_IRQ				SPI_INT_VEC(23)
#define PMU1_IRQ			SPI_INT_VEC(24)
#define L2CC_INTR_IRQ			SPI_INT_VEC(25)
#define L2CC_INTR1_IRQ			SPI_INT_VEC(26)
#define AXI_EXTERR_IRQ			SPI_INT_VEC(27)
#define GPIO4_IRQ			SPI_INT_VEC(28)
/* SPI_INT_VEC(29) ~ SPI_INT_VEC(30) are NULL */
#define AXI_INTERR_IRQ			SPI_INT_VEC(31)

#define IDSP_VIN_MVSYNC_IRQ		SPI_INT_VEC(32)
#define IDSP_VIN_VSYNC_IRQ		SPI_INT_VEC(33)
#define IDSP_VIN_SOF_IRQ		SPI_INT_VEC(34)
#define IDSP_VIN_DVSYNC_IRQ		SPI_INT_VEC(35)
#define IDSP_VIN_LAST_PIXEL_IRQ		SPI_INT_VEC(36)
#define GDMA_IRQ			SPI_INT_VEC(37)
#define IDSP_PIP_MVSYNC_IRQ		SPI_INT_VEC(38)
#define IDSP_PIP_VSYNC_IRQ		SPI_INT_VEC(39)
#define IDSP_PIP_SOF_IRQ		SPI_INT_VEC(40)
#define IDSP_PIP_DVSYNC_IRQ		SPI_INT_VEC(41)
#define IDSP_PIP_LAST_PIXEL_IRQ		SPI_INT_VEC(42)
#define VOUT_TV_SYNC_IRQ		SPI_INT_VEC(43)
#define VOUT_LCD_SYNC_IRQ		SPI_INT_VEC(44)
#define CODE_VDSP_0_IRQ			SPI_INT_VEC(45)
#define CODE_VDSP_1_IRQ			SPI_INT_VEC(46)
#define CODE_VDSP_2_IRQ			SPI_INT_VEC(47)
#define CODE_VDSP_3_IRQ			SPI_INT_VEC(48)
#define GPIO3_IRQ			SPI_INT_VEC(49)
#define GPIO2_IRQ			SPI_INT_VEC(50)
#define GPIO1_IRQ			SPI_INT_VEC(51)
#define GPIO0_IRQ			SPI_INT_VEC(52)
#define VIN_IRQ				SPI_INT_VEC(53)
#define ORC_VOUT0_IRQ			SPI_INT_VEC(54)
#define VOUT_IRQ			SPI_INT_VEC(55)
#define VDSP_PIP_CODING_IRQ		SPI_INT_VEC(56)
#define ADC_LEVEL_IRQ			SPI_INT_VEC(57)
#define HDMI_IRQ			SPI_INT_VEC(58)
#define WDT_IRQ				SPI_INT_VEC(59)
#define ETH_PMT_IRQ			SPI_INT_VEC(60)
#define UART0_IRQ			SPI_INT_VEC(61)
#define MOTOR_IRQ			SPI_INT_VEC(62)
#define TIMER8_IRQ			SPI_INT_VEC(63)

#define PWC_ALRAM			SPI_INT_VEC(64)
#define ETH_IRQ				SPI_INT_VEC(65)
#define USB_EHCI_IRQ			SPI_INT_VEC(66)
#define USB_OHCI_IRQ			SPI_INT_VEC(67)
#define USBC_IRQ			SPI_INT_VEC(68)
#define DMA_IRQ				SPI_INT_VEC(69)
#define DMA_FIOS_IRQ			SPI_INT_VEC(70)
#define FIOS_ECC_IRQ			SPI_INT_VEC(71)
#define FIOCMD_IRQ			SPI_INT_VEC(72)
#define FIODMA_IRQ			SPI_INT_VEC(73)
#define SDXC_IRQ			SPI_INT_VEC(74)
#define SD_IRQ				SPI_INT_VEC(75)
#define NOR_SPI				SPI_INT_VEC(76)
#define SSI_MASTER1_IRQ			SPI_INT_VEC(77)
#define SSI_MASTER0_IRQ			SPI_INT_VEC(78)
#define SSI_SLAVE_IRQ			SPI_INT_VEC(79)
#define UART1_IRQ			SPI_INT_VEC(80)
#define IDC2_IRQ			SPI_INT_VEC(81)
#define IDC1_IRQ			SPI_INT_VEC(82)
#define IDC0_IRQ			SPI_INT_VEC(83)
#define IRIF_IRQ			SPI_INT_VEC(84)
#define I2STX_IRQ			SPI_INT_VEC(85)
#define I2SRX_IRQ			SPI_INT_VEC(86)
#define USBVBUS_IRQ			SPI_INT_VEC(87)
#define USB_DIGITAL_ID_CHANGE_IRQ	SPI_INT_VEC(88)
#define USB_CONNECT_CHANGE_IRQ		SPI_INT_VEC(89)
#define USB_CHARGE_IRQ			SPI_INT_VEC(90)
#define SDXC_CD_IRQ			SPI_INT_VEC(91)
#define SD_CD_IRQ			SPI_INT_VEC(92)
#define UART2_IRQ			SPI_INT_VEC(93)
#define SSI_MASTER2_IRQ			SPI_INT_VEC(94)
#define IDC3_IRQ			SPI_INT_VEC(95)

#define NR_IRQS				SPI_INT_VEC(96)

#elif (CHIP_REV == CV1)
#define AXI0_EXTERR_IRQ			SPI_INT_VEC(2)
#define AXI1_EXTERR_IRQ			SPI_INT_VEC(3)
#define PMU0_0_IRQ			SPI_INT_VEC(4)
#define PMU0_1_IRQ			SPI_INT_VEC(5)
#define L2CC0_INTR_IRQ			SPI_INT_VEC(6)
#define L2CC0_INTR1_IRQ			SPI_INT_VEC(7)
#define PMU1_0_IRQ			SPI_INT_VEC(8)
#define PMU1_1_IRQ			SPI_INT_VEC(9)
#define L2CC1_INTR_IRQ			SPI_INT_VEC(10)
#define L2CC1_INTR1_IRQ			SPI_INT_VEC(11)
#define AXI0_INTERR_IRQ			SPI_INT_VEC(12)
#define AXI1_INTERR_IRQ			SPI_INT_VEC(13)
#define ADC_LEVEL_IRQ			SPI_INT_VEC(14)
#define MOTOR_IRQ			SPI_INT_VEC(15)
#define IDC0_IRQ			SPI_INT_VEC(16)
#define IDC1_IRQ			SPI_INT_VEC(17)
#define IDC2_IRQ			SPI_INT_VEC(18)
#define IDC3_IRQ			SPI_INT_VEC(19)
#define IDCS_IRQ			SPI_INT_VEC(20)
#define IRIF_IRQ			SPI_INT_VEC(21)
#define UART0_IRQ			SPI_INT_VEC(22)
#define TIMER1_IRQ			SPI_INT_VEC(23)
#define TIMER2_IRQ			SPI_INT_VEC(24)
#define TIMER3_IRQ			SPI_INT_VEC(25)
#define TIMER4_IRQ			SPI_INT_VEC(26)
#define TIMER5_IRQ			SPI_INT_VEC(27)
#define TIMER6_IRQ			SPI_INT_VEC(28)
#define TIMER7_IRQ			SPI_INT_VEC(29)
#define TIMER8_IRQ			SPI_INT_VEC(30)
#define TIMER9_IRQ			SPI_INT_VEC(31)

#define TIMER10_IRQ			SPI_INT_VEC(32)
#define TIMER11_IRQ			SPI_INT_VEC(33)
#define TIMER12_IRQ			SPI_INT_VEC(34)
#define TIMER13_IRQ			SPI_INT_VEC(35)
#define TIMER14_IRQ			SPI_INT_VEC(36)
#define TIMER15_IRQ			SPI_INT_VEC(37)
#define TIMER16_IRQ			SPI_INT_VEC(38)
#define TIMER17_IRQ			SPI_INT_VEC(39)
#define TIMER18_IRQ			SPI_INT_VEC(40)
#define TIMER19_IRQ			SPI_INT_VEC(41)
#define TIMER20_IRQ			SPI_INT_VEC(42)
#define WDT_IRQ				SPI_INT_VEC(43)
#define GPIO0_IRQ			SPI_INT_VEC(44)
#define GPIO1_IRQ			SPI_INT_VEC(45)
#define GPIO2_IRQ			SPI_INT_VEC(46)
#define GPIO3_IRQ			SPI_INT_VEC(47)
#define GPIO4_IRQ			SPI_INT_VEC(48)
#define GPIO5_IRQ			SPI_INT_VEC(49)
#define GPIO6_IRQ			SPI_INT_VEC(50)
#define USB_DIGITAL_ID_CHANGE_IRQ	SPI_INT_VEC(51)
#define USBVBUS_IRQ			SPI_INT_VEC(52)
#define USB_CONNECT_CHANGE_IRQ		SPI_INT_VEC(53)
#define USB_CHARGE_IRQ			SPI_INT_VEC(54)
#define SDXC_CD_IRQ			SPI_INT_VEC(55)
#define SD_CD_IRQ			SPI_INT_VEC(56)
#define ETH_PMT_IRQ			SPI_INT_VEC(57)
#define ETH_IRQ				SPI_INT_VEC(58)
#define UART0_AHB_IRQ			SPI_INT_VEC(59)
#define UART1_AHB_IRQ			SPI_INT_VEC(60)
#define UART2_AHB_IRQ			SPI_INT_VEC(61)
#define UART3_AHB_IRQ			SPI_INT_VEC(62)
#define UART4_AHB_IRQ			SPI_INT_VEC(63)

#define UART5_AHB_IRQ			SPI_INT_VEC(64)
#define USB_EHCI_IRQ			SPI_INT_VEC(65)
#define USB_OHCI_IRQ			SPI_INT_VEC(66)
#define USBC_IRQ			SPI_INT_VEC(67)
#define FIO_IRQ				SPI_INT_VEC(68)
#define FIO_ECC_IRQ			SPI_INT_VEC(69)
#define GDMA_IRQ			SPI_INT_VEC(70)
#define SDXC_IRQ			SPI_INT_VEC(71)
#define SD_IRQ				SPI_INT_VEC(72)
#define NOR_SPI				SPI_INT_VEC(73)
#define SSI_MASTER0_IRQ			SPI_INT_VEC(74)
#define SSI_MASTER1_IRQ			SPI_INT_VEC(75)
#define SSI_MASTER2_IRQ			SPI_INT_VEC(76)
#define SSI_MASTER3_IRQ			SPI_INT_VEC(77)
#define SSI_MASTER4_IRQ			SPI_INT_VEC(78)
#define SSI_MASTER5_IRQ			SPI_INT_VEC(79)
#define SSI_SLAVE_IRQ			SPI_INT_VEC(80)
#define I2STX_IRQ			SPI_INT_VEC(81)
#define I2SRX_IRQ			SPI_INT_VEC(82)
#define DMA0_IRQ			SPI_INT_VEC(83)
#define DMA1_IRQ			SPI_INT_VEC(84)
#define HDMI_IRQ			SPI_INT_VEC(85)
#define CANC0_IRQ			SPI_INT_VEC(86)
#define CANC1_IRQ			SPI_INT_VEC(87)
#define VOUT_TV_SYNC_IRQ		SPI_INT_VEC(88)
#define VOUT_LCD_SYNC_IRQ		SPI_INT_VEC(89)
#define RNG_IRQ				SPI_INT_VEC(90)
#define AXI_SOFT_IRQ0			SPI_INT_VEC(91)
#define AXI_SOFT_IRQ1			SPI_INT_VEC(92)
#define AXI_SOFT_IRQ2			SPI_INT_VEC(93)
#define AXI_SOFT_IRQ3			SPI_INT_VEC(94)
#define AXI_SOFT_IRQ4			SPI_INT_VEC(95)

#define AXI_SOFT_IRQ5			SPI_INT_VEC(96)
#define AXI_SOFT_IRQ6			SPI_INT_VEC(97)
#define AXI_SOFT_IRQ7			SPI_INT_VEC(98)
#define AXI_SOFT_IRQ8			SPI_INT_VEC(99)
#define AXI_SOFT_IRQ9			SPI_INT_VEC(100)
#define AXI_SOFT_IRQ10			SPI_INT_VEC(101)
#define AXI_SOFT_IRQ11			SPI_INT_VEC(102)
#define AXI_SOFT_IRQ12			SPI_INT_VEC(103)
#define AXI_SOFT_IRQ13			SPI_INT_VEC(104)
#define DRAM_ERROR_IRQ			SPI_INT_VEC(105)
#define VP0_IRQ				SPI_INT_VEC(106)
#define VP1_IRQ				SPI_INT_VEC(107)
#define ROLLING_SHUTTER_IRQ		SPI_INT_VEC(108)
#define FDET_IRQ			SPI_INT_VEC(109)
#define IDSP_VIN_MVSYNC_IRQ		SPI_INT_VEC(110)
#define IDSP_VIN_VSYNC_IRQ		SPI_INT_VEC(111)
#define IDSP_VIN_STAT_IRQ		SPI_INT_VEC(112)
#define IDSP_VIN_SOF_IRQ		SPI_INT_VEC(113)
#define IDSP_VIN_LAST_PIXEL_IRQ		SPI_INT_VEC(114)
#define IDSP_VIN_DVSYNC_IRQ		SPI_INT_VEC(115)
#define IDSP_PIP3_VSYNC_IRQ		SPI_INT_VEC(116)
#define IDSP_PIP3_STAT_IRQ		SPI_INT_VEC(117)
#define IDSP_PIP3_SOF_IRQ		SPI_INT_VEC(118)
#define IDSP_PIP3_LAST_PIXEL_IRQ	SPI_INT_VEC(119)
#define IDSP_PIP3_DVSYNC_IRQ		SPI_INT_VEC(120)
#define IDSP_PIP2_VSYNC_IRQ		SPI_INT_VEC(121)
#define IDSP_PIP2_STAT_IRQ		SPI_INT_VEC(122)
#define IDSP_PIP2_SOF_IRQ		SPI_INT_VEC(123)
#define IDSP_PIP2_LAST_PIXEL_IRQ	SPI_INT_VEC(124)
#define IDSP_PIP2_DVSYNC_IRQ		SPI_INT_VEC(125)
#define IDSP_PIP_MVSYNC_IRQ		SPI_INT_VEC(126)
#define IDSP_PIP_VSYNC_IRQ		SPI_INT_VEC(127)

#define IDSP_PIP_STAT_IRQ		SPI_INT_VEC(128)
#define IDSP_PIP_SOF_IRQ		SPI_INT_VEC(129)
#define IDSP_PIP_LAST_PIXEL_IRQ		SPI_INT_VEC(130)
#define IDSP_PIP_DVSYNC_IRQ		SPI_INT_VEC(131)
#define IDSP_MINI_VIN_VSYNC_IRQ		SPI_INT_VEC(132)
#define IDSP_MINI_VIN_STAT_IRQ		SPI_INT_VEC(133)
#define IDSP_MINI_VIN_SOF_IRQ		SPI_INT_VEC(134)
#define IDSP_MINI_VIN_LAST_PIXEL_IRQ	SPI_INT_VEC(135)
#define IDSP_MINI_VIN_DVSYNC_IRQ	SPI_INT_VEC(136)
#define SMEM_ERROR_IRQ			SPI_INT_VEC(137)
#define MINI_VIN_IRQ			SPI_INT_VEC(138)
#define VIN_IRQ				SPI_INT_VEC(139)
#define CODE_VDSP_0_IRQ			SPI_INT_VEC(140)
#define CODE_VDSP_1_IRQ			SPI_INT_VEC(141)
#define CODE_VDSP_2_IRQ			SPI_INT_VEC(142)
#define CODE_VDSP_3_IRQ			SPI_INT_VEC(143)
#define VOUT_LCD_IRQ			SPI_INT_VEC(144)
#define VOUT_TV_IRQ			SPI_INT_VEC(145)
#define VOUT_C_IRQ			SPI_INT_VEC(146)
#define VOUT_D_IRQ			SPI_INT_VEC(147)
#define VDSP_PIP_CODING_IRQ		SPI_INT_VEC(148)
#define VDSP_PIP2_CODING_IRQ		SPI_INT_VEC(149)
#define VDSP_PIP3_CODING_IRQ		SPI_INT_VEC(150)
#define L2C_ERR_IRQ			SPI_INT_VEC(151)
#define VORC_THREAD0_IRQ		SPI_INT_VEC(152)
#define VORC_THREAD1_IRQ		SPI_INT_VEC(153)
#define VORC_THREAD2_IRQ		SPI_INT_VEC(154)
#define VORC_THREAD3_IRQ		SPI_INT_VEC(155)
#define SORC_THREAD0_IRQ		SPI_INT_VEC(156)
#define SORC_THREAD1_IRQ		SPI_INT_VEC(157)
#define SORC_THREAD2_IRQ		SPI_INT_VEC(158)
#define SORC_THREAD3_IRQ		SPI_INT_VEC(159)
#define PWC_ALRAM			SPI_INT_VEC(160)

#define NR_IRQS				SPI_INT_VEC(161)

/* ==========================================================================*/
#else
#error "Not supported!"

#endif

/* ==========================================================================*/
#ifndef __ASM__

#endif
#endif
